// ⚠️ 此文件由 `bun run gen:toolnames` **自动生成**，请勿手改。
// 事实源：`getAllBuiltinToolLoaders()`（全量视图：含条件工具、与 flag 无关）
// 生成命令：`bun run gen:toolnames`（脚本：`app/scripts/gen-tool-names.ts`）

/** 内建工具名（编译期枚举源）—— **全量**：含"条件工具"（flag 未启用时运行期不可见者） */
export const TOOL_NAMES = [
  'agent',
  'ask_user_question',
  'audio_play',
  'bash',
  'brief',
  'broadcast',
  'browser',
  'browser_vision',
  'canvas',
  'channel',
  'clipboard',
  'code_run',
  'computer_use',
  'config',
  'create_project',
  'create_task_list',
  'cron_create',
  'cron_delete',
  'cron_list',
  'cron_stop',
  'doc_generate',
  'enter_worktree',
  'exit_worktree',
  'file_convert',
  'file_edit',
  'file_read',
  'file_write',
  'get_task_list',
  'glob',
  'grep',
  'image',
  'image_analysis',
  'image_display',
  'image_generate',
  'image_svg_generate',
  'knowledge_save',
  'list_mcp_resources',
  'list_peers',
  'lsp',
  'mcp_resource',
  'mcp_tool',
  'monitor',
  'music',
  'notebook',
  'plan',
  'powershell',
  'read_mcp_resource',
  'read_project_file',
  'repl',
  'save_conversation',
  'sessions',
  'sessions_yield',
  'skill',
  'skill_view',
  'skills_list',
  'sleep',
  'sleep_for',
  'sleep_until',
  'task_stop',
  'todo_write',
  'tool_search',
  'trace_recording',
  'tungsten',
  'update_task_status',
  'video',
  'video_analysis',
  'video_display',
  'video_generate',
  'web_fetch',
  'web_search',
  'write_project_file',
] as const;

/** 内建工具名联合类型 —— 写出不存在 / 拼错的工具名 ⇒ `bun run typecheck` 报错 */
export type ToolName = (typeof TOOL_NAMES)[number];

/** 生成时的工具名总数（门禁守卫用：与真实清单不符 ⇒ 需重新生成） */
export const TOOL_NAMES_COUNT = 71;
