export interface Session {
  id: string;
  title: string;
  createdAt: string;
  updatedAt: string;
  messageCount: number;
  roundCount: number;
  agentId?: string;
  source?: string;
  tokenUsage?: {
    totalInput: number;
    totalOutput: number;
  };
  /** 标记该会话标题是否已由 AI 自动生成或用户手动重命名 */
  titleAutoGenerated?: boolean;
}