/** 工作模式：plan（计划）/ do（执行） */
export type WorkMode = "plan" | "do";

export interface Session {
  id: string;
  /** 会话的 Plan/Do 工作模式（源：metadata.workMode 展平） */
  workMode?: WorkMode;
  title: string;
  createdAt: string;
  updatedAt: string;
  messageCount: number;
  roundCount: number;
  agentId?: string;
  agentName?: string;
  source?: string;
  tokenUsage?: {
    totalInput: number;
    totalOutput: number;
  };
  /** 标记该会话标题是否已由 AI 自动生成或用户手动重命名 */
  titleAutoGenerated?: boolean;

  /** M1-T1.3（2026-08-31）：列表置顶标记（源：metadata.pinned 展平） */
  pinned?: boolean;

  /** ===== 会话绑定资源（用于会话级模型和工作空间管理） ===== */

  /** 该会话绑定的模型 ID（空表示使用全局默认模型） */
  modelId?: string;

  /** 该会话绑定的 Provider ID（与 modelId 配合使用） */
  providerId?: string;

  /** 该会话所属的工作空间 ID（空表示不属于任何工作空间） */
  workspaceId?: string;

  /**
   * N-64（2026-09-20）：该会话所属**项目 ID** —— 项目归属的**权威事实面**
   * （后端 `effectiveProjectId()` 即按 `metadata.projectId` 优先判定，legacy
   * `workspaceId` 的 `project-` 前缀仅作兜底）。
   */
  projectId?: string;

  /** 该会话绑定的工作空间物理路径 */
  workspacePath?: string;

  /** 该会话的任务分工覆盖（仅覆盖部分任务类型，未覆盖的走全局配置） */
  tasksOverride?: Partial<import("./model").TaskModelConfig>;

  /** ===== 运行时元数据 ===== */

  /** 会话元数据（后端 DataSessionMetadata 投影） */
  metadata?: {
    workMode?: WorkMode;
    roundCount?: number;
    rollbackCount?: number;
    isStreaming?: boolean;
    roundIndex?: Record<string, number>;
    roundCounter?: number;
    /** A1 临时对话：temporary 会话不入历史/记忆/FTS（持久化标记，CS02） */
    temporary?: boolean;
  };
}
