export interface Session {
  id: string;
  title: string;
  createdAt: string;
  updatedAt: string;
  messageCount: number;
  roundCount: number;
  agentId?: string;
  source?: string;
  tokenUsage?: {
    totalInput: number;
    totalOutput: number;
  };
  /** 标记该会话标题是否已由 AI 自动生成或用户手动重命名 */
  titleAutoGenerated?: boolean;

  /** ===== 会话绑定资源（用于会话级模型和工作空间管理） ===== */

  /** 该会话绑定的模型 ID（空表示使用全局默认模型） */
  modelId?: string;

  /** 该会话绑定的 Provider ID（与 modelId 配合使用） */
  providerId?: string;

  /** 该会话所属的工作空间 ID（空表示不属于任何工作空间） */
  workspaceId?: string;

  /** 该会话绑定的工作空间物理路径 */
  workspacePath?: string;

  /** 该会话的任务分工覆盖（仅覆盖部分任务类型，未覆盖的走全局配置） */
  tasksOverride?: Partial<import("./model").TaskModelConfig>;
}