export type {
  ChannelId,
  DmPolicy,
  ChannelMeta,
  ChannelMessageToolHints,
  ChannelCapabilities,
  MessageContext,
  SendResult,
  InteractiveCard,
  ChannelStatus,
  ResolvedSender,
  IChannelConfigAdapter,
  IChannelLifecycleAdapter,
  IChannelOutboundAdapter,
  IChannelSecurityAdapter,
  IChannelPairingAdapter,
  IChannelInboundAdapter,
  InboundProtocol,
  IChannelPlugin,
} from './IChannel';
