/**
 * Chat History Slice — 会话历史与重命名工具函数
 *
 * 无 Zustand 状态字段，仅提供工具函数导出。
 * 被 chat-message.slice 引用（flushSaveBlocks、shouldAutoRename 等）。
 */
import { useRootStore } from "../root-store";
import { chatService } from "../../services/chatService";
import { sessionService } from "../../services/sessionService";
import { handleClientError } from "@/utils/handleError";
import type { Message } from "../../types";
import type { MessageBlock } from "../../types";

// 会话消息缓存：避免快速切换时重复 fetch
const _sessionMessageCache = new Map<string, Message[]>();
const MAX_CACHED_SESSIONS = 5;

/** 导出供 sessionStore 使用：获取缓存的会话消息 */
export function _getCachedMessages(sessionId: string): Message[] | null {
  return _sessionMessageCache.get(sessionId) ?? null;
}

/** 标记会话缓存为 stale（发送新消息后调用） */
export function staleSessionCache(sessionId: string): void {
  _sessionMessageCache.delete(sessionId);
}

/** 写入会话消息缓存（带 LRU 淘汰） */
export function setSessionCache(sessionId: string, messages: Message[]): void {
  if (
    _sessionMessageCache.size >= MAX_CACHED_SESSIONS &&
    !_sessionMessageCache.has(sessionId)
  ) {
    const oldest = _sessionMessageCache.keys().next().value;
    if (oldest) _sessionMessageCache.delete(oldest);
  }
  _sessionMessageCache.set(sessionId, messages);
}

// 防抖保存 blocks：流式传输中实时持久化，避免用户切换会话时丢失
let _pendingSaveSessionId: string | null = null;
let _pendingSaveMessageId: string | null = null;
let _pendingSaveBlocksVal: MessageBlock[] | null = null;
let hasPendingSave = false;
let _saveIsFlushing = false;

/** 设置待保存的 blocks */
export function setPendingSave(
  sessionId: string | null,
  messageId: string | null,
  blocks: MessageBlock[] | null,
): void {
  _pendingSaveSessionId = sessionId;
  _pendingSaveMessageId = messageId;
  _pendingSaveBlocksVal = blocks;
}

/** 获取待保存的 blocks（供 flush 内部使用） */
export function getPendingSave(): {
  sessionId: string | null;
  messageId: string | null;
  blocks: MessageBlock[] | null;
} {
  return {
    sessionId: _pendingSaveSessionId,
    messageId: _pendingSaveMessageId,
    blocks: _pendingSaveBlocksVal,
  };
}

/** 设置 hasPendingSave 标记 */
export function setHasPendingSave(value: boolean): void {
  hasPendingSave = value;
}

/** 获取 hasPendingSave 标记 */
export function getHasPendingSave(): boolean {
  return hasPendingSave;
}

/** 获取 _saveIsFlushing 标记 */
export function getIsFlushing(): boolean {
  return _saveIsFlushing;
}

/** 设置 _saveIsFlushing 标记 */
export function setIsFlushing(value: boolean): void {
  _saveIsFlushing = value;
}

/**
 * 立即 flush 待保存的 blocks
 */
export async function flushSaveBlocks(): Promise<void> {
  // 重入锁：防止高频触发导致并发写入冲突
  if (_saveIsFlushing) return;
  _saveIsFlushing = true;
  try {
    const { sessionId, messageId, blocks } = getPendingSave();
    if (sessionId && messageId && blocks) {
      setPendingSave(null, null, null);
      try {
        await chatService.updateMessageBlocks(
          sessionId,
          messageId,
          blocks as unknown as Array<Record<string, unknown>>,
        );
      } catch (err) {
        handleClientError(
          err,
          { module: "stores:chat:history", action: "flushSaveBlocks" },
          "warn",
        );
      }
    }
  } finally {
    _saveIsFlushing = false;
    // 如果在 flush 期间有新的待保存数据，递归处理
    if (hasPendingSave) {
      await flushSaveBlocks();
    }
  }
}

/**
 * 根据持久化的 titleAutoGenerated 标记判断是否需要自动重命名
 */
export async function shouldAutoRename(sessionId?: string): Promise<boolean> {
  if (!sessionId) {
    return false;
  }

  // 动态导入避免循环依赖（chat → sessionStore）
  const { useSessionStore } = await import("../sessionStore");
  const store = useSessionStore.getState();

  // 优先从 currentSession 查找
  if (store.currentSession?.id === sessionId) {
    return store.currentSession.titleAutoGenerated === false;
  }

  // 降级：从 sessions 列表中按 sessionId 查找
  const found = store.sessions.find((s) => s.id === sessionId);
  if (found) {
    return found.titleAutoGenerated === false;
  }

  // 会话未找到，不触发自动重命名
  return false;
}

/**
 * 自动生成会话标题，失败时用用户消息前30字符作为降级标题
 * 添加延迟 + 二次检查防御后端 autoGenerateTitle 的竞态条件
 */
export async function doAutoRename(
  sessionId: string,
  userMessage: string,
  assistantResponse: string,
): Promise<void> {
  // 延迟 2 秒，给后端 fire-and-forget 的 autoGenerateTitle 时间先完成
  await new Promise((r) => setTimeout(r, 2000));

  // 二次检查：后端可能已通过 SSE 更新了标记
  if (!(await shouldAutoRename(sessionId))) {
    return;
  }

  try {
    const title = await sessionService.generateTitle(
      sessionId,
      userMessage,
      assistantResponse,
    );

    const finalTitle =
      title || userMessage.slice(0, 30) + (userMessage.length > 30 ? "…" : "");
    useRootStore.getState().renameSession(sessionId, finalTitle);
  } catch (_error) {
    handleClientError(
      _error,
      { module: "stores:chat:history", action: "doAutoRename" },
      "warn",
    );
    // LLM 生成标题失败，用用户消息前30字符降级
    const fallbackTitle =
      userMessage.length > 30 ? userMessage.slice(0, 30) + "…" : userMessage;
    useRootStore.getState().renameSession(sessionId, fallbackTitle);
  }
}
