// MIT License
// Copyright (c) 2026 190615273@qq.com
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

/**
 * DANGEROUS_COMMAND_PATTERNS — 危险命令模式
 * 从 AutoModeClassifier.ts 提取（FSZ-003 拆分）。
 */

/**
 * 危险命令模式列表
 */
export const DANGEROUS_COMMAND_PATTERNS = [
  // P0 紧急新增：Remove-Item 别名全覆盖
  'remove-item',
  'ri ',
  'del ',
  'erase ',
  'rd ',
  'rmdir ',
  // 原始模式列表
  'rm -rf',
  'rm -fr',
  'rm -rf /',
  'rm -rf *',
  'rm -rf /*',
  'del /s /q',
  'erase /f /s',
  'rd /s /q',
  'format',
  'mkfs',
  'mkfs.ext',
  'mkfs.xfs',
  'dd if=',
  'dd of=/dev/',
  'dd of=/dev/sd',
  'dd of=/dev/hd',
  'chmod 777',
  'chmod -R 777',
  'chmod a+rwx',
  'chown -R',
  'chgrp -R',
  'chown root',
  'chgrp root',
  'truncate -s 0',
  'fallocate -l 0',
  ':(){ :|:& };:',
  'forkbomb',
  '(){ :|:& };:',
  'sudo',
  'su root',
  'pkexec',
  'doas',
  'su -',
  'sudo -i',
  'curl | bash',
  'wget | bash',
  'curl | sh',
  'wget | sh',
  'curl | sudo',
  'wget | sudo',
  'curl | su',
  'wget | su',
  'base64 -d |',
  'echo ... | base64',
  'echo | base64 -d',
  'python -c',
  'python3 -c',
  'perl -e',
  'ruby -e',
  'node -e',
  'bash -c',
  'sh -c',
  'zsh -c',
  'ksh -c',
  'curl -sL',
  'curl -s',
  'wget -q',
  'wget -qO-',
  'curl http',
  'curl https',
  'wget http',
  'wget https',
  'eval ',
  'exec ',
  'source ',
  '. ',
  '$(',
  '`',
  '${',
  '${{',
  '$((',
  '$(<',
  '${!',
  '=rm',
  '=sh',
  '=bash',
  '=cp',
  '=mv',
  '=cat',
  '=echo',
  'PATH=',
  'LD_PRELOAD=',
  'LD_LIBRARY_PATH=',
  'LD_AUDIT=',
  'PYTHONPATH=',
  'PERL5LIB=',
  'RUBYLIB=',
  'NODE_PATH=',
  'IFS=',
  'HOME=',
  'USER=',
  'SHELL=',
  'LOGNAME=',
  'LD_PRELOAD=',
  'LD_SHOW_AUXV=',
  'LD_DEBUG=',
  '/etc/',
  '/sys/',
  '/proc/',
  '/usr/bin/',
  '/usr/sbin/',
  '/bin/',
  '/sbin/',
  '/var/',
  '/boot/',
  '/lib/',
  '/lib64/',
  '/root/',
  '/home/',
  '/tmp/',
  '/var/tmp/',
  '/run/',
  'C:\\',
  'D:\\',
  '\\\\.\\',
  '\\\\?\\',
  '/dev/',
  '/mnt/',
  '/media/',
  '/opt/',
  '/usr/local/',
  '../',
  '..\\',
  '/../',
  '\\..\\',
  '..//',
  './/..',
  ' | ',
  ' > ',
  ' >> ',
  ' < ',
  ' << ',
  ' <<< ',
  ' >&',
  ' 2>&',
  ' & ',
  ' && ',
  ' || ',
  ' ;& ',
  ' ;&& ',
  'crontab',
  'at ',
  'batch ',
  'anacron',
  'nc ',
  'netcat ',
  'telnet ',
  'ftp ',
  'sftp ',
  'ssh ',
  'ncat ',
  'socat ',
  'curl ',
  'wget ',
  'systemctl start',
  'systemctl stop',
  'systemctl restart',
  'systemctl enable',
  'systemctl disable',
  'service ',
  'service start',
  'service stop',
  'service restart',
  '>/dev/null',
  '2>/dev/null',
  '>/dev/null 2>&1',
  '2>&1 /dev/null',
  '>/dev/zero',
  '2>/dev/zero',
  '>/dev/null >&',
  'echo -n',
  'echo -e',
  'printf ',
  'xxd -r',
  'xxd -p',
  'urlencode',
  'urldecode',
  'htmlencode',
  'htmldecode',
  'openssl enc',
  'openssl des',
  'openssl aes',
  'gpg -c',
  'ptrace',
  'inject',
  'hook',
  'LD_PRELOAD',
  '/proc/mem',
  '/dev/mem',
  '/dev/kmem',
  'kmod',
  'insmod',
  'rmmod',
  'modprobe',
  'tcpdump ',
  'tshark ',
  'wireshark ',
  'nmap ',
  'masscan ',
  'zmap ',
  'unicornscan ',
  'hping ',
  'arpspoof ',
  'dnsspoof ',
  'tcpspoof ',
  'ping -f',
  'ping -s',
  'flood',
  'synflood',
  'ddos',
  'UNION SELECT',
  'DROP TABLE',
  'INSERT INTO',
  'UPDATE ',
  'DELETE ',
  'OR 1=1',
  'AND 1=1',
  "OR 'x'='x",
  '<script>',
  '</script>',
  'javascript:',
  'onclick=',
  'onload=',
  'alert(',
  'prompt(',
  'confirm(',
  '%2e%2e',
  '%2e%2e/',
  '%2f',
  '%5c',
  '..%2f',
  '..%5c',
  '%u002e',
  '%u002f',
  '%c0%ae',
  '%c0%af',
  ' ; ',
  ' ;; ',
  ' | ',
  ' || ',
  ' & ',
  ' && ',
  ' ` ',
  ' $(',
  '`',
  '`',
  '＀',
  'include(',
  'require(',
  'include_once(',
  'require_once(',
  'shell_exec(',
  'exec(',
  'passthru(',
  'system(',
  'proc_open(',
  'popen(',
  'pcntl_exec(',
  'create_function(',
  'serialize(',
  'unserialize(',
  '__wakeup',
  '__destruct',
  '__construct',
  '"O":',
  '"C":',
  'O:[0-9]+:',
  'C:[0-9]+:',
  '"a":',
  '"s":',
  '"i":',
  '"d":',
  '"N";',
  '{{',
  '}}',
  '{%',
  '%}',
  '{%%',
  '%%}',
  'eval(',
  'new Function(',
  'setTimeout(',
  'setInterval(',
  'ReflectionClass',
  'getMethod',
  'invoke',
  'call_user_func',
  'array_filter',
  'array_map',
  'usort',
  'uasort',
  'uksort',
  '${IFS}',
  '${RANDOM}',
  '${UID}',
  '${USER}',
  '${HOME}',
  '$_',
  '$0',
  '$1',
  '$@',
  '$*',
  '$#',
  '$$',
  'sleep ',
  'usleep ',
  'nanosleep ',
  'pause ',
  'wait ',
  'yes ',
  'cat /dev/zero',
  'dd if=/dev/zero',
  'while true',
  'env',
  'printenv',
  'export',
  'declare -x',
  '/etc/passwd',
  '/etc/shadow',
  '/etc/group',
  '/etc/gshadow',
  '/etc/hosts',
  '/etc/resolv.conf',
  '/etc/ssh/',
  '/etc/sudoers',
  '/root/.ssh/',
  '/home/*/.ssh/',
  '/var/log/',
  '/var/log/auth.log',
  'cat /root/.ssh/id_rsa',
  'cat /home/*/.ssh/id_rsa',
  'rm /var/log/',
  'cat /dev/null >',
  'truncate -s 0',
  'iptables -F',
  'iptables -X',
  'ip6tables -F',
  'ip6tables -X',
  'ufw disable',
  'firewall-cmd --set-default-zone=trusted',
  'echo PermitRootLogin yes >>',
  'echo PasswordAuthentication yes >>',
  'useradd ',
  'userdel ',
  'usermod ',
  'groupadd ',
  'groupdel ',
  'groupmod ',
  'passwd ',
  'chpasswd',
  'openssl passwd',
  'ssh-keygen -f',
  'ssh-keygen -t',
  'mkfifo',
  'named pipe',
  'reverse shell',
  'bind shell',
  'script ',
  'scriptreplay ',
  'ttyrec ',
  'xinput ',
  'evtest ',
  'sniff ',
  'keylog ',
  'screencap ',
  'scrot ',
  'import ',
  'xwd ',
  'fswebcam ',
  'cheese ',
  'guvcview ',
  'arecord ',
  'sox ',
  'ffmpeg ',
  'aplay ',
  'mpg123 ',
  'ffplay ',
  'lsusb ',
  'usb-devices ',
  'usbmount ',
  'mount /dev/cdrom',
  'mount /dev/dvd',
  'eject ',
  'lsblk ',
  'fdisk ',
  'parted ',
  'blkid ',
  'df ',
  'du ',
  'mdadm ',
  'lvm ',
  'vgcreate ',
  'lvcreate ',
  'fsck ',
  'e2fsck ',
  'xfs_repair ',
  'mkfs ',
  'mke2fs ',
  'mkfs.ext4 ',
  'mkfs.xfs ',
  'mkfs.btrfs ',
  'sfdisk ',
  'cfdisk ',
  'gdisk ',
  'parted ',
  'shred ',
  'dd if=/dev/urandom',
  'dd if=/dev/zero',
  'testdisk ',
  'photorec ',
  'foremost ',
  'scalpel ',
  'tar ',
  'cpio ',
  'dump ',
  'restore ',
  'rsync ',
  'gzip ',
  'bzip2 ',
  'xz ',
  'zip ',
  'unzip ',
  '7z ',
  'rar ',
  'unrar ',
  'gpg -c',
  'openssl enc',
  'zip -e',
  '7z -p',
  'mount.nfs ',
  'mount.cifs ',
  'mount.smbfs ',
  'mount.sshfs ',
  'hdfs ',
  'glusterfs ',
  'ceph ',
  'nfs ',
  'git ',
  'svn ',
  'hg ',
  'bzr ',
  'apt ',
  'apt-get ',
  'dpkg ',
  'rpm ',
  'yum ',
  'dnf ',
  'pacman ',
  'zypper ',
  'npm install',
  'pip install',
  'gem install',
  'cargo install',
  'go get',
  'npm uninstall',
  'pip uninstall',
  'gem uninstall',
  'cargo uninstall',
  'apt upgrade',
  'apt dist-upgrade',
  'yum update',
  'dnf update',
  'pacman -Syu',
  'apt install linux-image',
  'yum install kernel',
  'dnf install kernel',
  'reboot',
  'shutdown',
  'halt',
  'poweroff',
  'init 6',
  'init 0',
  'systemctl status',
  'service status',
  'uptime',
  'who ',
  'w ',
  'uname ',
  'hostname ',
  'domainname ',
  'dnsdomainname ',
  'lspci ',
  'lsusb ',
  'dmidecode ',
  'hdparm ',
  'smartctl ',
  'lscpu ',
  'free ',
  'cat /proc/cpuinfo',
  'cat /proc/meminfo',
  'cat /proc/version',
  'cat /proc/cmdline',
  'ps ',
  'top ',
  'htop ',
  'pidof ',
  'pgrep ',
  'pkill ',
  'free ',
  'vmstat ',
  'mpstat ',
  'iostat ',
  'df ',
  'ifconfig ',
  'ip ',
  'route ',
  'netstat ',
  'ss ',
  'arp ',
  'hostname -I',
  'ping ',
  'traceroute ',
  'mtr ',
  'curl ',
  'wget ',
  'nc -zv',
  'dig ',
  'nslookup ',
  'host ',
  'dnsmasq ',
  'systemctl ',
  'service ',
  'chkconfig ',
  'update-rc.d ',
  'journalctl ',
  'dmesg ',
  'tail -f /var/log/',
  'cat /var/log/',
  'logrotate ',
  'rsyslogd ',
  'syslogd ',
  'useradd ',
  'userdel ',
  'usermod ',
  'groupadd ',
  'groupdel ',
  'groupmod ',
  'passwd ',
  'id ',
  'whoami ',
  'who ',
  'last ',
  'lastlog ',
  'groups ',
  'getent group',
  'getent passwd',
  'chmod ',
  'chown ',
  'chgrp ',
  'chattr ',
  'setfacl ',
  'getfacl ',
  'ls ',
  'dir ',
  'pwd ',
  'cd ',
  'mkdir ',
  'rmdir ',
  'touch ',
  'ln ',
  'mv ',
  'cp ',
  'rm ',
  'cat ',
  'head ',
  'tail ',
  'less ',
  'more ',
  'view ',
  'nano ',
  'vi ',
  'vim ',
  'emacs ',
  'find ',
  'grep ',
  'egrep ',
  'fgrep ',
  'locate ',
  'which ',
  'whereis ',
  'diff ',
  'cmp ',
  'comm ',
  'diff3 ',
  'sdiff ',
  'sed ',
  'awk ',
  'cut ',
  'paste ',
  'sort ',
  'uniq ',
  'tr ',
  'wc ',
  'iconv ',
  'dos2unix ',
  'unix2dos ',
  'toascii ',
  'toupper ',
  'tolower ',
  'md5sum ',
  'sha1sum ',
  'sha256sum ',
  'sha512sum ',
  'cksum ',
  'sum ',
  'openssl ',
  'gpg ',
  'cryptsetup ',
  'keytool ',
  'keystore ',
  'date ',
  'cal ',
  'time ',
  'timeout ',
  'sleep ',
  'usleep ',
  'bc ',
  'dc ',
  'expr ',
  'let ',
  'tr ',
  'sed ',
  'awk ',
  'cut ',
  'paste ',
  'join ',
  'split ',
  'csplit ',
  'sort ',
  'uniq ',
  'comm ',
  'diff ',
  'cmp ',
  'wc ',
  'uniq -c',
  'sort -n',
  'gcc ',
  'g++ ',
  'clang ',
  'make ',
  'cmake ',
  'autoconf ',
  'automake ',
  'python ',
  'perl ',
  'ruby ',
  'node ',
  'php ',
  'lua ',
  'tcl ',
  'awk ',
  'sed ',
  'gdb ',
  'lldb ',
  'strace ',
  'ltrace ',
  'valgrind ',
  'perf ',
  'dtrace ',
  'top ',
  'htop ',
  'iotop ',
  'iftop ',
  'vmstat ',
  'iostat ',
  'mpstat ',
  'pidstat ',
  'prometheus ',
  'grafana-cli ',
  'influx ',
  'telegraf ',
  'collectd ',
  'fluentd ',
  'logstash ',
  'filebeat ',
  'journalctl ',
  'nmap ',
  'nessus ',
  'openvas ',
  'metasploit ',
  'sqlmap ',
  'burpsuite ',
  'john ',
  'hashcat ',
  'hydra ',
  'medusa ',
  'crunch ',
  'wordlist ',
  'dd ',
  'strings ',
  'hexdump ',
  'xxd ',
  'foremost ',
  'testdisk ',
  'objdump ',
  'readelf ',
  'nm ',
  'ld ',
  'strip ',
  'upx ',
  'msfconsole ',
  'exploit ',
  'payload ',
  'shellcode ',
  'proxychains ',
  'tor ',
  'sshuttle ',
  'chisel ',
  'frp ',
  'ngrok ',
  'phishing ',
  'spoof ',
  'social-engineer ',
  'evilginx ',
  'virus ',
  'malware ',
  'ransomware ',
  'trojan ',
  'worm ',
  'botnet ',
];
