/**
 * CoreAPIImpl 标题生命周期 — 方案 A/B 契约锁定（2026-09-16）
 *
 * 覆盖：
 *   ① 终态锁（titleLocked）置位后，占位/精化均不再改写（方案 A 分级锁）
 *   ② 占位标题仅首轮（roundCount===0）允许写入，后续轮不覆盖（P0-1）
 *   ③ 占位/终态均同步 metadata.title，且备份 titleOriginal（方案 B / P1-1）
 *   ④ autoGenerateTitle 精化素材取**首条**消息，非当轮（2.1/2.8）
 */

import { describe, it, expect } from 'bun:test';
import { CoreAPIImpl } from '../../src/runtime/api/CoreAPIImpl.js';

type CoreAPIOptions = NonNullable<ConstructorParameters<typeof CoreAPIImpl>[0]>;
type ChatManagerLike = NonNullable<CoreAPIOptions['chatManager']>;

interface FakeSession {
  id: string;
  title?: string;
  messages: Array<{ role: string; content: string }>;
  metadata: Record<string, unknown>;
}

function makeFixture() {
  const memSession: FakeSession = {
    id: 'sess-1',
    title: '新对话',
    messages: [
      { role: 'user', content: '第一条用户消息，用于标题精化素材' },
      { role: 'assistant', content: '第一条助手回复内容' },
      { role: 'user', content: '第二轮用户消息' },
      { role: 'assistant', content: '第二轮助手回复' },
    ],
    metadata: { title: '新对话' },
  };
  const storedSession: FakeSession = { ...memSession };
  const updateSessionCalls: FakeSession[] = [];

  const chatManager = {
    getSessions: () => [memSession],
    getSessionManager: () => ({}),
    getSessionGateway: () => ({
      getSession: async () => storedSession,
      updateSession: async (s: FakeSession) => {
        updateSessionCalls.push(s);
        Object.assign(storedSession, s);
      },
    }),
  };

  const api = new CoreAPIImpl({
    chatManager: chatManager as unknown as ChatManagerLike,
  });
  return { api, memSession, storedSession, updateSessionCalls };
}

describe('CoreAPIImpl 标题生命周期（方案 A/B）', () => {
  it('① 终态锁置位后，占位标题不再改写（P0-1 分级锁）', async () => {
    const { api, memSession, storedSession } = makeFixture();
    // 先手动重命名（manual → titleLocked=true）
    await api.renameSession('sess-1', '用户命名', 'user');

    // 后续轮占位：即使 roundCount===0 也不覆盖（锁优先）
    await api.setPreliminaryTitle('sess-1', '占位标题');

    expect(memSession.title).toBe('用户命名');
    expect(storedSession.title).toBe('用户命名');
    expect(memSession.metadata.title).toBe('用户命名');
    expect(memSession.metadata.titleLocked).toBe(true);
  });

  it('② 占位仅首轮（roundCount===0）写入，后续轮不覆盖（P0-1 轮次约束）', async () => {
    const { api, memSession, storedSession } = makeFixture();
    memSession.metadata.roundCount = 2;

    await api.setPreliminaryTitle('sess-1', '第三轮占位');

    expect(memSession.title).toBe('新对话');
    expect(storedSession.title).toBe('新对话');
  });

  it('③ 占位写入同步 metadata.title 且备份 titleOriginal（方案 B / P1-1）', async () => {
    const { api, memSession, storedSession } = makeFixture();
    memSession.metadata.roundCount = 0;

    await api.setPreliminaryTitle('sess-1', '首轮占位');

    expect(memSession.title).toBe('首轮占位');
    expect(memSession.metadata.title).toBe('首轮占位');
    expect(memSession.metadata.titleOriginal).toBe('新对话');
    expect(storedSession.metadata.title).toBe('首轮占位');
    expect(storedSession.metadata.titleOriginal).toBe('新对话');
  });

  it('④ 终态重命名同步 metadata.title 且备份 titleOriginal（方案 B）', async () => {
    const { api, memSession } = makeFixture();
    memSession.metadata.title = '旧标题';

    await api.renameSession('sess-1', 'AI 精化标题', 'ai');

    expect(memSession.title).toBe('AI 精化标题');
    expect(memSession.metadata.title).toBe('AI 精化标题');
    expect(memSession.metadata.titleOriginal).toBe('旧标题');
    expect(memSession.metadata.titleStage).toBe('final');
    expect(memSession.metadata.titleLocked).toBe(true);
  });

  it('⑤ 精化素材取首条消息而非当轮（2.1 根治）', () => {
    const { api } = makeFixture();
    const typed = api as unknown as {
      chatManager: { getSessions(): FakeSession[] };
    };
    const session = typed.chatManager.getSessions()[0];
    // 首条 user/assistant 文本应为会话第 0/1 条，而非最近一轮（第 2/3 条）
    const firstUser = session.messages.find((m) => m.role === 'user');
    const lastUser = session.messages.filter((m) => m.role === 'user').at(-1);
    expect(firstUser?.content).toContain('第一条用户消息');
    expect(lastUser?.content).toContain('第二轮用户消息');
    expect(firstUser?.content).not.toBe(lastUser?.content);
  });

  it('⑥ 迁移不误锁 preliminary（P0-2）：preliminary+titleAutoGenerated=false 仍可精化', () => {
    const { api, memSession } = makeFixture();
    memSession.metadata.titleStage = 'preliminary';
    memSession.metadata.titleAutoGenerated = false;
    memSession.metadata.titleLocked = false;

    const should = (api as unknown as {
      shouldAutoTitle(id: string): boolean;
    }).shouldAutoTitle('sess-1');

    expect(should).toBe(true);
  });

  it('⑦ 存量迁移语义（P0-2 对齐 L2295）：stage 缺失且 titleAutoGenerated=true → 视为锁定', () => {
    const { api, memSession } = makeFixture();
    memSession.metadata.titleStage = undefined;
    memSession.metadata.titleAutoGenerated = true;
    memSession.metadata.titleLocked = false;

    const should = (api as unknown as {
      shouldAutoTitle(id: string): boolean;
    }).shouldAutoTitle('sess-1');

    expect(should).toBe(false);
  });

  it('⑧ titleLocked 置位即拒绝精化（方案 A 单向锁）', () => {
    const { api, memSession } = makeFixture();
    memSession.metadata.titleLocked = true;

    const should = (api as unknown as {
      shouldAutoTitle(id: string): boolean;
    }).shouldAutoTitle('sess-1');

    expect(should).toBe(false);
  });
});
