from docx import Document
doc = Document()
doc.add_heading('这是一篇 Word 文档', 0)
doc.add_paragraph('用来测试 Liri 的文件预览功能。')
doc.add_heading('功能列表', 1)
doc.add_paragraph('默认收起侧边栏', style='List Bullet')
doc.add_paragraph('点击文件自动展开', style='List Bullet')
doc.add_paragraph('拖拽调整面板宽度', style='List Bullet')
doc.add_paragraph('Markdown 渲染', style='List Bullet')
doc.add_paragraph('非文本文件类型探测', style='List Bullet')
doc.add_heading('结语', 2)
doc.add_paragraph('看看这个 docx 在文件预览面板里能不能正常显示内容。')
doc.save(r'E:\PY\CODES\PY_APP\测试文档.docx')
print('Word 文档已生成')
