import type { UnifiedMessage } from './Message.ts';
export type { UnifiedMessage };

/**
 * 会话类型枚举
 */
export enum SessionType {
  LOCAL = 'local',
  REMOTE = 'remote',
  BRIDGE = 'bridge',
  CHAT = 'chat',
}

/**
 * 会话状态枚举
 *
 * @deprecated 使用 {@link SessionState} — 从 `@modules/state/session` 导入
 */
export enum SessionStatus {
  ACTIVE = 'active',
  PAUSED = 'paused',
  ENDED = 'ended',
  ARCHIVED = 'archived',
  IDLE = 'idle',
  RUNNING = 'running',
  REQUIRES_ACTION = 'requires_action',
  COMPLETED = 'completed',
  ERROR = 'error',
  ABORTED = 'aborted',
}

/**
 * 会话元数据接口
 *
 * @deprecated 使用 {@link DataSessionMetadata} — 从 `@modules/core/data-models` 导入
 */
export interface SessionMetadata {
  title?: string;
  tags?: string[];
  mode?: string;
  model?: string;
  workspaceId?: string;
  providerId?: string;
  tasksOverride?: unknown;
  worktreeState?: string;
  prLink?: string;
  projectPath?: string;
  userId?: string;
  createdBy?: string;
  parentSessionId?: string;
  /** D3（2026-08-24）：fork 血缘——源事件前缀数（子会话继承 [1..seedLength] 事件） */
  seedLength?: number;
  sessionType?: SessionType;
  crashRecovery?: string;
  crashedAt?: string;
  lastActivityBeforeCrash?: string;
  resumedAt?: string;
  /** 标题是否已自动生成（true 表示不再触发自动命名） */
  titleAutoGenerated?: boolean;
  /**
   * E-3（2026-08-23）：标题生成阶段（方案 D2-B）
   * - preliminary：占位标题（发消息时立即设置，回复后可精化覆盖）
   * - final：LLM 精化完成（不再覆盖）
   * - manual：用户手动改名（永不覆盖）
   * 存量迁移：titleAutoGenerated 缺失/为 true → 视为 final（不覆盖）
   */
  titleStage?: 'preliminary' | 'final' | 'manual';
}

/**
 * 会话存储信息
 */
export interface SessionStorageInfo {
  type: 'database' | 'filesystem' | 'memory' | 'hybrid';
  path?: string;
  lastSyncedAt?: number;
}

/**
 * 统一会话接口
 *
 * @deprecated 使用 {@link DataSession} — 从 `@modules/core/data-models` 导入
 */
export interface UnifiedSession {
  id: string;
  type: SessionType;
  title?: string;
  agentId?: string;
  createdAt: number;
  updatedAt: number;
  lastActivityAt: number;
  status: SessionStatus;
  metadata: SessionMetadata;
  storage?: SessionStorageInfo;
}

/**
 * 会话配置接口
 */
export interface SessionConfig {
  maxHistoryLength?: number;
  autoSave?: boolean;
  autoSaveInterval?: number;
  enableCompression?: boolean;
  maxStorageSize?: number;
  sessionType?: SessionType;
}

/**
 * 会话过滤条件
 *
 * @deprecated 使用 {@link DataSessionFilter} — 从 `@modules/core/data-models` 导入
 */
export interface SessionFilter {
  type?: SessionType;
  status?: SessionStatus;
  tags?: string[];
  mode?: string;
  startDate?: number;
  endDate?: number;
  userId?: string;
  agentId?: string;
  searchQuery?: string;
}

/**
 * 会话统计信息
 *
 * @deprecated 使用 {@link DataSessionStats} — 从 `@modules/core/data-models` 导入
 */
export interface SessionStats {
  totalSessions: number;
  activeSessions: number;
  archivedSessions: number;
  averageSessionDuration: number;
  totalMessages: number;
  lastActivityAt?: number;
  sessions?: string[];
}

/**
 * 创建会话参数
 *
 * @deprecated 使用 {@link DataCreateSessionParams} — 从 `@modules/core/data-models` 导入
 */
export interface CreateSessionParams {
  id?: string;
  type?: SessionType;
  title?: string;
  metadata?: Partial<SessionMetadata>;
  config?: SessionConfig;
}

/**
 * 会话信息（用于列表展示）
 *
 * @deprecated 使用 {@link DataSessionInfo} — 从 `@modules/core/data-models` 导入
 */
export interface SessionInfo {
  id: string;
  title?: string;
  type: SessionType;
  status: SessionStatus;
  createdAt: number;
  updatedAt: number;
  lastActivityAt: number;
  messageCount: number;
  metadata: SessionMetadata;
}

/**
 * 会话状态变更监听器
 */
export type SessionStateChangedListener = (
  sessionId: string,
  oldState: SessionStatus,
  newState: SessionStatus,
  details?: Record<string, unknown>
) => void;

/**
 * 会话元数据变更监听器
 */
export type SessionMetadataChangedListener = (
  sessionId: string,
  metadata: SessionMetadata
) => void;

/**
 * 会话消息监听器
 */
export type SessionMessageListener = (
  sessionId: string,
  message: UnifiedMessage
) => void;

/**
 * 会话使用统计监听器
 */
export type SessionUsageListener = (
  sessionId: string,
  stats: SessionUsageStats
) => void;

/**
 * 会话使用统计
 */
export interface SessionUsageStats {
  messageCount: number;
  tokenUsage?: number;
  toolCalls?: number;
  errors?: number;
  lastMessageAt?: number;
}

/**
 * 需要操作详情
 */
export interface RequiresActionDetails {
  reason: string;
  actionType: string;
  options?: Record<string, unknown>;
}
