// MIT License
// Copyright (c) 2026 190615273@qq.com
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

/**
 * CoreAPIImpl 批 B4 纯搬迁（2026-10-05）：C17 标题 / 元数据 / 执行阶段追踪。
 *
 * 自同目录 `CoreAPIImpl.ts` 外迁 —— 方法体逐字保留（仅把 `this.<宿主依赖>` 改写为
 * `this.deps.<getter>()`）。宿主依赖经 {@link SessionTitlingDeps} 的 getter 注入
 * （宿主 `chatManager` 本身即懒解析 getter ⇒ 用 getter 注入零初始化顺序陷阱）。
 *
 * 宿主保留 `renameSession` / `setPreliminaryTitle` / `shouldAutoTitle` / `updateSessionMeta` /
 * `generateSessionTitle` 五个对外薄转发（`CoreAPIImpl implements CoreAPI` + 生产/测试消费者）。
 * `_executionPhaseTrackers`（Map）随迁并由本模块**拥有** —— 宿主 C2（`chat`/`chatStream`）经
 * `getExecutionPhaseTracker` 消费、C16（`deleteSession`/`clearAllSessions`）经 `deleteTracker` /
 * `clearTrackers` 释放（单向消费，无宿主写路径）。
 */

import type { ChatManager } from '@modules/chat';
import { ExecutionPhaseTracker } from '@modules/session';
import type { LiriEvent } from '@modules/session/types/events';
import type { Message } from '@modules/session/types/message';
import { getLogger } from '@modules/monitoring';
import { handleError } from '@modules/error';

const logger = getLogger('runtime:api:CoreAPIImpl');

/** 提取消息纯文本（兼容 string 与 ContentBlock[]） */
function messagePlainText(message: Message | undefined): string | undefined {
  if (!message?.content) return undefined;
  if (typeof message.content === 'string')
    return message.content.trim() || undefined;
  return (
    message.content
      .map((block) => ('value' in block ? block.value : ''))
      .join('')
      .trim() || undefined
  );
}

/** 取会话首条用户消息文本（2.1/2.8：精化素材须基于首条，非当轮） */
function firstUserText(
  session: { messages: Message[] } | undefined
): string | undefined {
  if (!session) return undefined;
  return messagePlainText(session.messages.find((m) => m.role === 'user'));
}

/** 取会话首条助手消息文本（2.1/2.8：精化素材须基于首条，非当轮） */
function firstAssistantText(
  session: { messages: Message[] } | undefined
): string | undefined {
  if (!session) return undefined;
  return messagePlainText(session.messages.find((m) => m.role === 'assistant'));
}

/**
 * B4（2026-10-05）：宿主依赖（全 getter，零初始化顺序陷阱）。
 */
export interface SessionTitlingDeps {
  getChatManager: () => ChatManager;
}

/**
 * B4（2026-10-05）：标题 / 元数据 / 执行阶段追踪（会话标题分级锁 / 占位与精化 / 元数据更新 /
 * per-session 执行阶段追踪器）。
 */
export class SessionTitling {
  constructor(private readonly deps: SessionTitlingDeps) {}

  /**
   * E-1 接入（2026-08-23）：per-session 执行阶段追踪器
   * 工具完成自动记录交付物 → 流结束时 buildDeliverableData 发射 deliverable chunk + 写事件。
   */
  private readonly _executionPhaseTrackers = new Map<
    string,
    ExecutionPhaseTracker
  >();

  /**
   * 重命名会话标题
   *
   * E-3（2026-08-23，方案 D2-B）：来源区分 + titleStage
   * - source='user' → 用户手动改名 → titleStage='manual'（preliminary/final 均不覆盖）
   * - source='ai' → AI 精化完成 → titleStage='final'（不再覆盖）
   * 存量 titleAutoGenerated=true → 一并迁移为 final。
   */
  async renameSession(
    sessionId: string,
    title: string,
    source: 'user' | 'ai' = 'user'
  ): Promise<void> {
    const stage: 'manual' | 'final' = source === 'user' ? 'manual' : 'final';
    // 方案 A（2026-09-15）：终态（manual/final）置单向锁，永不回退；占位绝不置锁。
    // 方案 B（修 2.7）：同步 metadata.title；备份原始值到 titleOriginal 供回滚（P1-1）。
    const current = this.deps
      .getChatManager()
      .getSessions()
      .find((s) => s.id === sessionId);
    const curMeta = current?.metadata as Record<string, unknown> | undefined;
    const metadataPatch: Record<string, unknown> = {
      titleStage: stage,
      // 存量兼容：同步保留旧标记，避免旧判断路径误覆盖
      titleAutoGenerated: true,
      titleLocked: true,
      title,
    };
    if (curMeta?.title != null && !curMeta.titleOriginal) {
      metadataPatch.titleOriginal = curMeta.title;
    }
    // 更新内存中的会话标题
    const session = current;
    if (session) {
      session.title = title;
      session.metadata = { ...session.metadata, ...metadataPatch };
    } else {
      logger.warn(
        `renameSession: 会话 ${sessionId} 不在内存中，仅持久化到存储`,
        { sessionId, title, source }
      );
    }

    // 持久化标题变更到存储
    try {
      const gateway = this.deps.getChatManager().getSessionGateway();
      if (gateway) {
        const storedSession = await gateway.getSession(sessionId);
        if (storedSession) {
          if (
            !(metadataPatch.titleOriginal as unknown) &&
            (storedSession.metadata as Record<string, unknown> | undefined)
              ?.title != null
          ) {
            metadataPatch.titleOriginal = (
              storedSession.metadata as Record<string, unknown>
            ).title;
          }
          storedSession.title = title;
          storedSession.metadata = {
            ...storedSession.metadata,
            ...metadataPatch,
          };
          await gateway.updateSession(storedSession);
        } else {
          logger.warn(
            `renameSession: 会话 ${sessionId} 不在存储中，持久化被跳过`,
            { sessionId, title }
          );
        }
      }
    } catch (e) {
      await handleError(e, {
        module: 'runtime:api',
        action: 'persist_session_title',
        context: { sessionId },
      });
    }

    // 广播事件通知前端更新左侧会话列表
    const { broadcastEvent } =
      await import('@modules/infrastructure/http/handlers/handler-utils');
    broadcastEvent('session:renamed', { id: sessionId, title });
    // D5（2026-08-24）：标题事件化——追加 session/title 事件（回放/审计轨迹）
    await this._appendTitleEvent(
      sessionId,
      title,
      source === 'user' ? 'manual' : 'final'
    );
  }

  /**
   * E-3（2026-08-23，方案 D2-B）：设置占位标题（preliminary，不调 LLM）
   *
   * 发消息时（LLM 调用前）立即调用，用户可立即看到新标题；
   * 回复完成后由 autoGenerateTitle 用 LLM 精化覆盖（若未变 manual/final）。
   */
  async setPreliminaryTitle(sessionId: string, title: string): Promise<void> {
    // 方案 A（2026-09-15）：
    //  - 分级锁：终态(tileLocked)拒绝被占位覆盖；占位绝不置锁。
    //  - P0-1：仅首轮（roundCount===0）允许写占位，标题一旦可读/已多轮绝不覆盖。
    //    这同时修复 2.8（崩溃停在 preliminary 的会话后续轮不再改写标题）。
    //  - P1-2：写入前原子复查以磁盘为准（gateway.getSession），对抗多端内存陈旧。
    const current = this.deps
      .getChatManager()
      .getSessions()
      .find((s) => s.id === sessionId);
    const curMeta = current?.metadata as Record<string, unknown> | undefined;
    if (curMeta?.titleLocked === true) return;
    if (((curMeta?.roundCount as number | undefined) ?? 0) > 0) return;

    const metadataPatch: Record<string, unknown> = {
      titleStage: 'preliminary',
      // 方案 B（修 2.7）：占位标题同样同步 metadata.title
      title,
    };
    if (curMeta?.title != null && !curMeta.titleOriginal) {
      metadataPatch.titleOriginal = curMeta.title;
    }

    // 持久化（含写入前原子复查）
    try {
      const gateway = this.deps.getChatManager().getSessionGateway();
      if (gateway) {
        const storedSession = await gateway.getSession(sessionId);
        if (storedSession) {
          const storedMeta = storedSession.metadata as
            | Record<string, unknown>
            | undefined;
          if (storedMeta?.titleLocked === true) return;
          if (((storedMeta?.roundCount as number | undefined) ?? 0) > 0) return;
          if (
            !(metadataPatch.titleOriginal as unknown) &&
            storedMeta?.title != null
          ) {
            metadataPatch.titleOriginal = storedMeta.title;
          }
          storedSession.title = title;
          storedSession.metadata = {
            ...storedSession.metadata,
            ...metadataPatch,
          };
          await gateway.updateSession(storedSession);
        }
      }
    } catch (e) {
      await handleError(e, {
        module: 'runtime:api',
        action: 'persist_preliminary_title',
        context: { sessionId },
      });
    }
    // 内存（与磁盘一致；持久化失败时仅更新内存，广播仍发生，保持旧语义）
    if (current) {
      current.title = title;
      current.metadata = { ...current.metadata, ...metadataPatch };
    }
    // 广播
    const { broadcastEvent } =
      await import('@modules/infrastructure/http/handlers/handler-utils');
    broadcastEvent('session:renamed', { id: sessionId, title });
    // D5（2026-08-24）：标题事件化——占位标题追加 session/title 事件
    await this._appendTitleEvent(sessionId, title, 'preliminary');
  }

  /**
   * E-3（2026-08-23，方案 D2-B）：占位标题清洗截断
   *
   * 去除首尾空白/常见敏感前缀，超 30 字截断加省略号；清洗后为空 → '新对话'。
   */
  public sanitizePlaceholderTitle(raw: string): string {
    let text = (raw ?? '')
      .trim()
      .replace(/^[#>*\- ]+/, '')
      .trim();
    if (!text) return '新对话';
    if (text.length > 30) {
      text = text.slice(0, 30) + '…';
    }
    return text;
  }

  /**
   * E-1 接入（2026-08-23）：获取 per-session 执行阶段追踪器（懒创建）
   */
  public getExecutionPhaseTracker(sessionId: string): ExecutionPhaseTracker {
    let tracker = this._executionPhaseTrackers.get(sessionId);
    if (!tracker) {
      tracker = new ExecutionPhaseTracker(sessionId, () => {
        // 阶段事件由流式 progress/execution_phase 通道推送，此处不额外处理
      });
      this._executionPhaseTrackers.set(sessionId, tracker);
    }
    return tracker;
  }

  /**
   * D-LIFE（2026-09-17）：会话删除 → 释放其执行阶段追踪器（防 per-session Map 永久驻留）
   */
  public deleteTracker(sessionId: string): void {
    this._executionPhaseTrackers.delete(sessionId);
  }

  /**
   * D-LIFE（2026-09-17）：清空会话 → 同步释放全部执行阶段追踪器
   */
  public clearTrackers(): void {
    this._executionPhaseTrackers.clear();
  }

  /**
   * T-1 修复（2026-08-23）：标题精化 in-flight 标记——首轮精化进行中（LLM 生成耗时
   * 2~30s）拒绝后续占位/精化，防止"非首轮标题被下一轮覆盖"竞态。精化完成/失败后
   * 由 autoGenerateTitle 删除。见 dev_docs/20260823/会话标题生成问题-排查报告-20260823.md。
   */
  private readonly _titleInFlight = new Set<string>();

  /**
   * E-3（2026-08-23，方案 D2-B）：是否需要生成/精化标题
   *
   * 返回 false 的条件：titleStage=final/manual，或存量 titleAutoGenerated=true（视为 final）。
   */
  public shouldAutoTitle(sessionId: string): boolean {
    // T-1 修复：精化 in-flight 期间不触发占位/新精化（竞态守卫）
    if (this._titleInFlight.has(sessionId)) return false;
    const session = this.deps
      .getChatManager()
      .getSessions()
      .find((s) => s.id === sessionId);
    if (!session) return false;
    const meta = session.metadata as Record<string, unknown> | undefined;
    // 方案 A：终态单向锁（titleLocked）优先放行即拒绝——占位/精化都不再改写
    if (meta?.titleLocked === true) return false;
    const stage = meta?.titleStage;
    if (stage === 'final' || stage === 'manual') return false;
    // 存量迁移：titleAutoGenerated=true 且无 titleStage → 视为 final
    if (stage === undefined && meta?.titleAutoGenerated === true) return false;
    return true;
  }

  /**
   * D5（2026-08-24）：追加 session/title 事件（标题事件化，log-only 回放审计）。
   *
   * 与 metadata.titleStage 快照双写：运行时读取仍走 metadata（性能），
   * 事件提供完整标题变更轨迹（对齐 deepseek-harness session/title）。
   * 写事件失败不阻断标题主流程（fire-and-forget + catch）。
   */
  private async _appendTitleEvent(
    sessionId: string,
    title: string,
    source: 'preliminary' | 'final' | 'manual'
  ): Promise<void> {
    try {
      const ts = await this.deps.getChatManager().getStreamTailSeq(sessionId);
      await this.deps.getChatManager().appendStreamEvent(sessionId, {
        type: 'session/title',
        seq: ts + 1,
        time: Date.now(),
        sessionId,
        data: { title, source },
      } as LiriEvent);
    } catch (e) {
      logger.debug('session/title 事件写入失败（不影响标题主流程）', {
        sessionId,
        title,
        source,
        error: String(e),
      });
    }
  }

  /**
   * 更新会话元数据（模型绑定、工作空间等）
   */
  async updateSessionMeta(
    sessionId: string,
    meta: {
      model?: string;
      workspaceId?: string;
      providerId?: string;
      tasksOverride?: Record<string, string>;
      pinned?: boolean;
      /** plan/do 工作模式（见 `.trae/specs/plan-do-mode.md`；输入区开关写入） */
      workMode?: 'plan' | 'do';
    }
  ): Promise<void> {
    // M1-T1.3（2026-08-31）：pinned 仅改列表分组标记，**不 touch updatedAt**——
    // 对齐 openworker conversations.py set_flags 语义：置顶/取消置顶不应导致
    // 会话在列表中因"最近更新"而重排（标题自动生成同理，由 rename 路径单独控制）。
    // 2026-10-04：workMode 属"配置类"字段（同 model/workspaceId/tasksOverride），
    // 计入 hasMetaField → 会 touch updatedAt。
    const hasMetaField =
      meta.model !== undefined ||
      meta.workspaceId !== undefined ||
      meta.providerId !== undefined ||
      meta.tasksOverride !== undefined ||
      meta.workMode !== undefined;
    const shouldTouchUpdatedAt = hasMetaField;

    // 1. 更新内存中的会话 metadata
    const session = this.deps
      .getChatManager()
      .getSessions()
      .find((s) => s.id === sessionId);
    if (session) {
      if (meta.model !== undefined) session.metadata.model = meta.model;
      if (meta.workspaceId !== undefined)
        session.metadata.workspaceId = meta.workspaceId;
      if (meta.providerId !== undefined)
        session.metadata.providerId = meta.providerId;
      if (meta.tasksOverride !== undefined)
        session.metadata.tasksOverride = meta.tasksOverride;
      if (meta.pinned !== undefined) session.metadata.pinned = meta.pinned;
      if (meta.workMode !== undefined)
        session.metadata.workMode = meta.workMode;
      if (shouldTouchUpdatedAt) session.updatedAt = new Date();
    }

    // 2. 持久化到存储
    try {
      const gateway = this.deps.getChatManager().getSessionGateway();
      if (gateway) {
        const storedSession = await gateway.getSession(sessionId);
        if (storedSession) {
          if (meta.model !== undefined)
            storedSession.metadata.model = meta.model;
          if (meta.workspaceId !== undefined)
            storedSession.metadata.workspaceId = meta.workspaceId;
          if (meta.providerId !== undefined)
            storedSession.metadata.providerId = meta.providerId;
          if (meta.tasksOverride !== undefined)
            storedSession.metadata.tasksOverride = meta.tasksOverride;
          if (meta.pinned !== undefined)
            storedSession.metadata.pinned = meta.pinned;
          if (meta.workMode !== undefined)
            storedSession.metadata.workMode = meta.workMode;
          await gateway.updateSession(storedSession);
        }
      }
    } catch (e) {
      await handleError(e, {
        module: 'runtime:api',
        action: 'update_session_meta',
        context: { sessionId },
      });
    }
  }

  async generateSessionTitle(
    sessionId: string,
    userMessage: string,
    assistantResponse: string
  ): Promise<string | null> {
    try {
      // 子批 F `runtime -> agent` 收口：唯一取用点，async 上下文 ⇒ 动态导入（本文件既有模式）
      const { getTitleGenerator } = await import('@modules/agent');
      const titleGenerator = getTitleGenerator();
      const title = await titleGenerator.generateTitle(
        userMessage,
        assistantResponse,
        async (messages) => {
          const llmClient = this.deps.getChatManager().getLLMClient();
          const response = await llmClient.sendMessage(
            messages as import('@modules/ai').ChatMessage[],
            {}
          );
          return response?.content || null;
        }
      );
      return title;
    } catch (error) {
      logger.warning('Failed to generate session title', error);
      return null;
    }
  }

  public autoGenerateTitle(
    sessionId: string,
    userMessage: string,
    assistantResponse: string
  ): void {
    // 后台 fire-and-forget：不影响流式响应速度
    setImmediate(async () => {
      // T-1 修复：精化开始前标记 in-flight（防后续占位/精化竞态覆盖）
      if (!this.shouldAutoTitle(sessionId)) {
        return;
      }
      this._titleInFlight.add(sessionId);
      try {
        // 2.1/2.8 根治（2026-09-16）：精化素材改从会话**首条**消息取，
        // 阻断"当轮消息喂 LLM → 标题跟最后一轮走"的直接机制。
        // 崩溃恢复会话（roundCount>1 仍 preliminary）同样基于首条对话精化，
        // 不再因"第 N 轮恢复触发精化"而生成第 N 轮标题。
        const session = this.deps
          .getChatManager()
          .getSessions()
          .find((s) => s.id === sessionId);
        const refineUser = firstUserText(session) ?? userMessage;
        const refineAssistant =
          firstAssistantText(session) ?? assistantResponse;
        const title =
          (await this.generateSessionTitle(
            sessionId,
            refineUser,
            refineAssistant
          )) ??
          // BUG-B 修复：generateSessionTitle 内部 catch 返回 null（从不抛异常），
          // 原 catch 分支的"首条消息前 30 字符"兜底永远不会执行。
          // 降级标题直接在此生成，LLM 失败时不再停留在"新对话"。
          refineUser.slice(0, 30) + (refineUser.length > 30 ? '…' : '');
        // P3-2 修复（前端交互专项 2026-08-30）：提交前复查 titleStage——
        // shouldAutoTitle 只在生成前检查（起点），LLM 生成期间（2~30s）用户手动
        // 重命名会把 titleStage 置为 manual，此时无条件 rename 会用 AI 标题覆盖
        // 用户标题。此处复查不能用 shouldAutoTitle（自身 _titleInFlight 会自阻塞），
        // 直接读 titleStage：manual/final 均跳过 AI 提交。
        const aiSession = this.deps
          .getChatManager()
          .getSessions()
          .find((s) => s.id === sessionId);
        const aiMeta = aiSession?.metadata as
          | Record<string, unknown>
          | undefined;
        const aiStage = aiMeta?.titleStage;
        if (
          aiStage === 'manual' ||
          aiStage === 'final' ||
          aiMeta?.titleLocked === true
        ) {
          logger.info('Auto title skipped: user renamed during generation', {
            sessionId,
            stage: aiStage,
          });
          return;
        }
        // AI 精化完成 → source='ai' → titleStage='final'（不再覆盖）
        await this.renameSession(sessionId, title, 'ai');
        logger.info('Auto-generated session title', { sessionId, title });
      } catch (_error) {
        // 仅 renameSession 等异常走到这里（标题已保证非空），不重复兜底
        logger.debug('Auto title generation skipped', { sessionId });
      } finally {
        // T-1 修复：精化结束（成功/失败）清除 in-flight，允许后续新一轮占位/精化
        this._titleInFlight.delete(sessionId);
      }
    });
  }
}
