import {
  TYPES_SECTION_INDIVIDUAL,
  WHAT_NOT_TO_SAVE_SECTION,
  WHEN_TO_ACCESS_SECTION,
  TRUSTING_RECALL_SECTION,
} from './memoryTypes.js';
import { DIR_EXISTS_GUIDANCE } from './MemoryPromptService.js';

/**
 * Team memory types section for memory prompts.
 */
export const TYPES_SECTION_TEAM = [
  '## Memory types',
  '',
  '### User memories (private)',
  'Information about the user themselves: their role, preferences, communication style, and goals.',
  '- Example: "The user is a frontend developer who prefers React over Vue"',
  '- Example: "The user likes detailed explanations with code examples"',
  '- Example: "The user is working on a tight deadline for this project"',
  '',
  '### Feedback memories (private)',
  'Feedback the user has given you about your performance or the tools you use.',
  '- Example: "The user prefers I not summarize code changes"',
  '- Example: "The user found my explanation of Promises helpful"',
  '- Example: "The user asked me to use more emojis in my responses"',
  '',
  '### Project memories (shared)',
  'Context about the project that is not derivable from the code itself.',
  '- Example: "The project uses a specific API that requires an API key"',
  '- Example: "The team follows a specific branching strategy"',
  '- Example: "There is a known issue with the third-party library"',
  '',
  '### Reference memories (shared)',
  'External references or resources that are relevant to the project.',
  '- Example: "The design specs are available at https://example.com/specs"',
  '- Example: "The API documentation is at https://api.example.com/docs"',
  '- Example: "The team uses Jira for project management: https://jira.example.com"',
];

/**
 * Build team memory lines with private and shared sections.
 */
export function buildTeamMemoryLines(
  displayName: string,
  privateMemoryDir: string,
  sharedMemoryDir: string,
  extraGuidelines?: string[],
  skipIndex = false
): string[] {
  const howToSave = skipIndex
    ? [
        '## How to save memories',
        '',
        'Write each memory to its own file (e.g., `user_role.md`, `feedback_testing.md`) using this frontmatter format:',
        '',
        '```yaml',
        '---',
        'id: user_preferences',
        'name: User Preferences',
        "description: The user's preferred working style and tools",
        'type: user',
        'createdAt: 2023-01-01T00:00:00Z',
        'updatedAt: 2023-01-01T00:00:00Z',
        'tags: [preferences, workflow]',
        'priority: high',
        'expiresAt: 2024-01-01T00:00:00Z',
        'author: assistant',
        'source: conversation',
        '---',
        '```',
        '',
        '- Keep the name, description, and type fields in memory files up-to-date with the content',
        '- Organize memory semantically by topic, not chronologically',
        '- Update or remove memories that turn out to be wrong or outdated',
        '- Do not write duplicate memories. First check if there is an existing memory you can update before writing a new one.',
      ]
    : [
        '## How to save memories',
        '',
        'Saving a memory is a two-step process:',
        '',
        '**Step 1** — write the memory to its own file (e.g., `user_role.md`, `feedback_testing.md`) using this frontmatter format:',
        '',
        '```yaml',
        '---',
        'id: user_preferences',
        'name: User Preferences',
        "description: The user's preferred working style and tools",
        'type: user',
        'createdAt: 2023-01-01T00:00:00Z',
        'updatedAt: 2023-01-01T00:00:00Z',
        'tags: [preferences, workflow]',
        'priority: high',
        'expiresAt: 2024-01-01T00:00:00Z',
        'author: assistant',
        'source: conversation',
        '---',
        '```',
        '',
        '**Step 2** — add a pointer to that file in `MEMORY.md`. `MEMORY.md` is an index, not a memory — each entry should be one line, under ~150 characters: `- [Title](file.md) — one-line hook`. It has no frontmatter. Never write memory content directly into `MEMORY.md`.',
        '',
        '- `MEMORY.md` is always loaded into your conversation context — lines after 200 will be truncated, so keep the index concise',
        '- Keep the name, description, and type fields in memory files up-to-date with the content',
        '- Organize memory semantically by topic, not chronologically',
        '- Update or remove memories that turn out to be wrong or outdated',
        '- Do not write duplicate memories. First check if there is an existing memory you can update before writing a new one.',
      ];

  const lines: string[] = [
    `# ${displayName}`,
    '',
    `You have two persistent, file-based memory systems:`,
    '',
    `**Private memory** (only visible to you and this user): \`${privateMemoryDir}\``,
    `**Shared team memory** (visible to all team members): \`${sharedMemoryDir}\``,
    '',
    `${DIR_EXISTS_GUIDANCE}`,
    '',
    "You should build up these memory systems over time so that future conversations can have a complete picture of who the user is, how they'd like to collaborate with you, what behaviors to avoid or repeat, and the context behind the work the user gives you.",
    '',
    'If the user explicitly asks you to remember something, save it immediately as whichever type fits best. If they ask you to forget something, find and remove the relevant entry.',
    '',
    '## Memory scope',
    '',
    '**Private memories** (user, feedback):',
    `- Store in: \`${privateMemoryDir}\``,
    '- Visible to: Only you and the user who created them',
    '- Use for: Personal preferences, individual feedback, sensitive information',
    '',
    '**Shared team memories** (project, reference):',
    `- Store in: \`${sharedMemoryDir}\``,
    '- Visible to: All team members',
    '- Use for: Project context, shared resources, team-wide information',
    '',
    ...TYPES_SECTION_TEAM,
    ...WHAT_NOT_TO_SAVE_SECTION,
    '',
    ...howToSave,
    '',
    ...WHEN_TO_ACCESS_SECTION,
    '',
    ...TRUSTING_RECALL_SECTION,
    '',
    '## Memory and other forms of persistence',
    'Memory is one of several persistence mechanisms available to you as you assist the user in a given conversation. The distinction is often that memory can be recalled in future conversations and should not be used for persisting information that is only useful within the scope of the current conversation.',
    '- When to use or update a plan instead of memory: If you are about to start a non-trivial implementation task and would like to reach alignment with the user on your approach you should use a Plan rather than saving this information to memory. Similarly, if you already have a plan within the conversation and you have changed your approach persist that change by updating the plan rather than saving a memory.',
    '- When to use or update tasks instead of memory: When you need to break your work in current conversation into discrete steps or keep track of your progress use tasks instead of saving to memory. Tasks are great for persisting information about the work that needs to be done in the current conversation, but memory should be reserved for information that will be useful in future conversations.',
    '',
    ...(extraGuidelines ?? []),
    '',
  ];

  return lines;
}
