/**
 * 共享类型定义
 *
 * Web (client/) 和 TUI (app/) 两端复用的核心类型。
 * 作为 API 契约的"单一事实来源"，所有跨端接口类型均在此定义。
 *
 * 管理规则（参见架构方案 §5.5.2）：
 * 1. Review 要求：shared-types 修改须经 app 和 client 两方 review
 * 2. CI 一致性检查：比较两端类型与 shared-types 是否一致
 * 3. 防绕过：禁止在 local types 中重复定义已有共享类型
 */

// ============================================================
// API 响应类型
// ============================================================

/** API 错误结构 */
export interface SharedApiError {
  code: number;
  message: string;
}

/** 统一 API 响应包装 */
export interface SharedApiResponse<T = unknown> {
  ok: boolean;
  data?: T;
  error?: SharedApiError;
}

// ============================================================
// 会话 (Session) 相关类型
// ============================================================

/** 会话摘要 — 用于列表展示 */
export interface SharedSession {
  id: string;
  title: string;
  createdAt: string;
  updatedAt: string;
  messageCount: number;
  roundCount: number;
  agentId?: string;
  source?: string;
  /** Token 消耗统计 */
  tokenUsage?: {
    totalInput: number;
    totalOutput: number;
  };
  /** 标记该会话标题是否已由 AI 自动生成或用户手动重命名 */
  titleAutoGenerated?: boolean;
}

// ============================================================
// 消息 (Message) 相关类型
// ============================================================

/** 消息角色 */
export type SharedMessageRole = "user" | "assistant" | "system" | "tool";

/** Token 消耗统计 */
export interface SharedTokenUsage {
  input: number;
  output: number;
  total: number;
  cacheRead?: number;
  cacheCreation?: number;
}

/** 工具调用信息 */
export interface SharedToolCallInfo {
  id: string;
  name: string;
  arguments: Record<string, unknown>;
}

/** 工具调用执行状态 */
export interface SharedToolCallStatus {
  toolCallId: string;
  toolName: string;
  progress: number;
  message: string;
  status: "running" | "completed" | "failed";
}

/** 基础消息 — 两端共用的核心字段 */
export interface SharedMessage {
  role: SharedMessageRole;
  content: string;
  tool_calls?: SharedToolCallInfo[];
  tool_call_id?: string;
  usage?: SharedTokenUsage;
}

// ============================================================
// Streaming 相关类型
// ============================================================

/** Stream 统计数据 */
export interface SharedStreamStats {
  startTime: number;
  tokenCount: number;
  currentSpeed: number;
}

/** Stream 状态枚举 */
export type SharedStreamState = "idle" | "streaming" | "paused" | "question" | "done";

// ============================================================
// 模型 (Model) 相关类型
// ============================================================

/** 模型信息摘要 */
export interface SharedModelInfo {
  id: string;
  name: string;
  provider: string;
  capabilities: string[];
}
