import {
  TYPES_SECTION_INDIVIDUAL,
  WHAT_NOT_TO_SAVE_SECTION,
  WHEN_TO_ACCESS_SECTION,
  TRUSTING_RECALL_SECTION,
} from './memoryTypes.js';
import { DIR_EXISTS_GUIDANCE } from './MemoryPromptBuilder.js';

/**
 * Team memory types section for memory prompts.
 */
export const TYPES_SECTION_TEAM = [
  '## 记忆类型',
  '',
  '### 用户记忆（User，私有）',
  '关于用户本人的信息：角色、偏好、沟通风格与目标。',
  '- 示例：“该用户是前端开发者，偏好 React 而非 Vue”',
  '- 示例：“该用户喜欢带代码示例的详细解释”',
  '- 示例：“该用户在这个项目上正赶一个很紧的截止日期”',
  '',
  '### 反馈记忆（Feedback，私有）',
  '用户就你的表现或你所使用工具给出的反馈。',
  '- 示例：“该用户希望我不要对代码改动做总结”',
  '- 示例：“该用户认为我对 Promise 的解释很有帮助”',
  '- 示例：“该用户要求我在回复中多用表情符号”',
  '',
  '### 项目记忆（Project，共享）',
  '无法从代码本身推导出的项目上下文。',
  '- 示例：“该项目使用某个需要 API key 的特定 API”',
  '- 示例：“团队遵循某个特定的分支策略”',
  '- 示例：“该第三方库存在一个已知问题”',
  '',
  '### 参考记忆（Reference，共享）',
  '与项目相关的外部引用或资源。',
  '- 示例：“设计规范见 https://example.com/specs”',
  '- 示例：“API 文档见 https://api.example.com/docs”',
  '- 示例：“团队用 Jira 做项目管理：https://jira.example.com”',
];

/**
 * Build team memory lines with private and shared sections.
 */
export function buildTeamMemoryLines(
  displayName: string,
  privateMemoryDir: string,
  sharedMemoryDir: string,
  extraGuidelines?: string[],
  skipIndex = false
): string[] {
  const howToSave = skipIndex
    ? [
        '## 如何保存记忆',
        '',
        '每条记忆写入独立文件（例如 `user_role.md`、`feedback_testing.md`），使用如下 frontmatter 格式：',
        '',
        '```yaml',
        '---',
        'id: user_preferences',
        'name: User Preferences',
        "description: The user's preferred working style and tools",
        'type: user',
        'createdAt: 2023-01-01T00:00:00Z',
        'updatedAt: 2023-01-01T00:00:00Z',
        'tags: [preferences, workflow]',
        'priority: high',
        'expiresAt: 2024-01-01T00:00:00Z',
        'author: assistant',
        'source: conversation',
        '---',
        '```',
        '',
        '- 保持记忆文件中的 name、description、type 字段与内容同步更新',
        '- 按主题（语义）而非时间顺序组织记忆',
        '- 对发现错误或已过时的记忆进行更新或删除',
        '- 不要写入重复记忆。写入新记忆前，先检查是否已有可更新的记忆。',
      ]
    : [
        '## 如何保存记忆',
        '',
        '保存一条记忆分两步：',
        '',
        '**第 1 步** —— 把记忆写入独立文件（例如 `user_role.md`、`feedback_testing.md`），使用如下 frontmatter 格式：',
        '',
        '```yaml',
        '---',
        'id: user_preferences',
        'name: User Preferences',
        "description: The user's preferred working style and tools",
        'type: user',
        'createdAt: 2023-01-01T00:00:00Z',
        'updatedAt: 2023-01-01T00:00:00Z',
        'tags: [preferences, workflow]',
        'priority: high',
        'expiresAt: 2024-01-01T00:00:00Z',
        'author: assistant',
        'source: conversation',
        '---',
        '```',
        '',
        '**第 2 步** —— 在 `MEMORY.md` 中为该文件添加一条指针。`MEMORY.md` 是索引而非记忆 —— 每项一行、约 150 字符以内：`- [Title](file.md) — one-line hook`。它没有 frontmatter。切勿把记忆内容直接写入 `MEMORY.md`。',
        '',
        '- `MEMORY.md` 始终会被载入你的对话上下文 —— 第 200 行之后会被截断，因此请保持索引精简',
        '- 保持记忆文件中的 name、description、type 字段与内容同步更新',
        '- 按主题（语义）而非时间顺序组织记忆',
        '- 对发现错误或已过时的记忆进行更新或删除',
        '- 不要写入重复记忆。写入新记忆前，先检查是否已有可更新的记忆。',
      ];

  const lines: string[] = [
    `# ${displayName}`,
    '',
    `你有两套持久化的、基于文件的记忆系统：`,
    '',
    `**私有记忆**（仅你与该用户可见）：\`${privateMemoryDir}\``,
    `**共享团队记忆**（所有团队成员可见）：\`${sharedMemoryDir}\``,
    '',
    `${DIR_EXISTS_GUIDANCE}`,
    '',
    '你应当逐步建立这两套记忆系统，使未来的对话能够完整掌握：用户是谁、希望如何与你协作、哪些行为应当避免或重复，以及用户交给你的工作背后的上下文。',
    '',
    '如果用户明确要求你记住某事，请立即按最合适的类型保存；如果用户要求你遗忘某事，请找到并删除相应条目。',
    '',
    '## 记忆范围',
    '',
    '**私有记忆**（user、feedback）：',
    `- 存放位置：\`${privateMemoryDir}\``,
    '- 可见范围：仅你与该条记忆的创建者',
    '- 适用于：个人偏好、个体反馈、敏感信息',
    '',
    '**共享团队记忆**（project、reference）：',
    `- 存放位置：\`${sharedMemoryDir}\``,
    '- 可见范围：所有团队成员',
    '- 适用于：项目上下文、共享资源、团队级信息',
    '',
    ...TYPES_SECTION_TEAM,
    ...WHAT_NOT_TO_SAVE_SECTION,
    '',
    ...howToSave,
    '',
    ...WHEN_TO_ACCESS_SECTION,
    '',
    ...TRUSTING_RECALL_SECTION,
    '',
    '## 记忆与其它持久化形式',
    '记忆是你在对话中协助用户时可用的多种持久化机制之一。区别通常在于：记忆可在**未来的对话**中被召回，因此不应用于保存仅在当前对话范围内有用的信息。',
    '- 何时应当用计划（Plan）而非记忆：若你即将开始一项非平凡的实现工作，并希望就方案与用户达成一致，应使用 Plan，而不是把该信息存入记忆。同理，若对话中已有计划而你又改变了方案，请通过更新计划来持久化该变更，而不是保存一条记忆。',
    '- 何时应当用任务（Task）而非记忆：若你需要把当前对话中的工作拆分为若干离散步骤，或需要跟踪进度，请使用任务而不是记忆。任务适合持久化"当前对话中待做的工作"这类信息，而记忆应留给**未来对话仍然有用**的信息。',
    '',
    ...(extraGuidelines ?? []),
    '',
  ];

  return lines;
}
