import type { Message, Session } from "../types";
import { http as apiHttp } from "./httpClient";
import { createLogger } from "../utils/logger";
import { handleClientError } from "../utils/handleError";
import { getOTelTracing } from "../monitoring/otel";

const logger = createLogger("sessionService");

const isTauri =
  typeof window !== "undefined" &&
  ("__TAURI__" in window || "__TAURI_INTERNALS__" in window);

// 是否已降级到内存模式（后端不可用时设为 true）
let _isUsingFallback = false;

/** 获取当前是否处于降级模式 */
export function isUsingFallback(): boolean {
  return _isUsingFallback;
}

async function getTauriCore() {
  if (!isTauri) return null;
  try {
    return await import("@tauri-apps/api/core");
  } catch (e) {
    handleClientError(e, {
      module: "services:session",
      action: "getTauriCore",
    });
    return null;
  }
}

function createMemorySessionService() {
  _isUsingFallback = true;
  return {
    list: async (): Promise<Session[]> => [],
    create: async (title: string): Promise<Session> => ({
      id: `local-${Date.now()}`,
      title,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      messageCount: 0,
      roundCount: 0,
    }),
    switch: async (_id: string): Promise<Session> => ({
      id: _id,
      title: "恢复的会话",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      messageCount: 0,
      roundCount: 0,
    }),
    delete: async (_id: string): Promise<void> => {},
    rename: async (_id: string, _title: string): Promise<void> => {},
    getCurrent: async (): Promise<Session | null> => null,
  };
}

async function tryTauri<T>(
  method: string,
  args?: Record<string, unknown>,
): Promise<T | null> {
  const core = await getTauriCore();
  if (!core) return null;
  try {
    return await core.invoke<T>(method, args);
  } catch (e) {
    handleClientError(e, { module: "services:session", action: "tryTauri" });
    return null;
  }
}

/**
 * 展平 metadata 字段到顶级（BUG #12 展平修复）
 * 后端在 metadata 中存储 titleAutoGenerated，统一提取到顶层字段
 * 同时提取 model → modelId, workspaceId, tasksOverride 等会话绑定资源
 */
function flattenSession<S extends Session | null>(session: S): S {
  if (!session) return session;
  const raw = session as unknown as {
    metadata?: {
      titleAutoGenerated?: boolean;
      model?: string;
      workspaceId?: string;
      providerId?: string;
      workspacePath?: string;
      tasksOverride?: Record<string, string>;
    };
  };
  return {
    ...session,
    titleAutoGenerated: raw.metadata?.titleAutoGenerated,
    modelId: raw.metadata?.model || session.modelId,
    providerId: raw.metadata?.providerId || session.providerId,
    workspaceId: raw.metadata?.workspaceId || session.workspaceId,
    workspacePath:
      raw.metadata?.workspacePath ||
      (session as { workspacePath?: string }).workspacePath,
    tasksOverride:
      (raw.metadata?.tasksOverride as Record<string, string> | undefined) ||
      session.tasksOverride,
  };
}

/**
 * 创建会话
 * @param title 会话标题
 * @param options 可选：绑定模型ID、工作空间ID
 */
export const sessionService = {
  list: (): Promise<Session[]> => {
    return getOTelTracing().asyncWrap("services:session:list", async () => {
      try {
        const res = await apiHttp.get<Session[]>("/v1/sessions");
        if (res.ok) {
          _isUsingFallback = false;
          return (res.data ?? []).map(flattenSession);
        }
        logger.warn("获取会话列表失败", { error: res.error });
      } catch (e) {
        handleClientError(e, { module: "services:session", action: "list" });
        // 网络错误，尝试降级
      }
      const result = await tryTauri<Session[]>("list_sessions");
      if (result) return result.map(flattenSession);
      return createMemorySessionService().list();
    });
  },

  create: (
    title: string,
    options?: {
      modelId?: string;
      workspaceId?: string;
      workspacePath?: string;
    },
  ): Promise<Session> => {
    return getOTelTracing().asyncWrap(
      "services:session:createSession",
      async () => {
        try {
          const body: Record<string, unknown> = { title };
          if (options?.modelId) body.model = options.modelId;
          if (options?.workspaceId) body.workspaceId = options.workspaceId;
          if (options?.workspacePath)
            body.workspace_path = options.workspacePath;
          const res = await apiHttp.post<Session>("/v1/sessions", body);
          if (res.ok) {
            _isUsingFallback = false;
            return flattenSession(res.data as Session);
          }
          logger.warn("创建会话失败", { error: res.error });
        } catch (e) {
          handleClientError(e, {
            module: "services:session",
            action: "create",
          });
          // 网络错误
        }
        const result = await tryTauri<Session>("create_session", { title });
        if (result) return flattenSession(result);
        return createMemorySessionService().create(title);
      },
    );
  },

  switch: (id: string): Promise<Session> => {
    return getOTelTracing().asyncWrap(
      "services:session:switchSession",
      async () => {
        try {
          const res = await apiHttp.post<Session>(`/v1/sessions/${id}/switch`);
          if (res.ok) {
            _isUsingFallback = false;
            return flattenSession(res.data as Session);
          }
          logger.warn("切换会话失败", { id, error: res.error });
        } catch (e) {
          handleClientError(e, {
            module: "services:session",
            action: "switch",
          });
          // 网络错误
        }
        const result = await tryTauri<Session>("switch_session", { id });
        if (result) return flattenSession(result);
        return createMemorySessionService().switch(id);
      },
    );
  },

  delete: (id: string): Promise<void> => {
    return getOTelTracing().asyncWrap(
      "services:session:deleteSession",
      async () => {
        try {
          const res = await apiHttp.delete<void>(`/v1/sessions/${id}`);
          if (res.ok) {
            _isUsingFallback = false;
            return;
          }
          logger.warn("删除会话失败", { id, error: res.error });
        } catch (e) {
          handleClientError(e, {
            module: "services:session",
            action: "delete",
          });
          // 网络错误
        }
        const result = await tryTauri<void>("delete_session", { id });
        if (result !== null) return;
        return createMemorySessionService().delete(id);
      },
    );
  },

  rename: (id: string, title: string): Promise<void> => {
    return getOTelTracing().asyncWrap(
      "services:session:renameSession",
      async () => {
        try {
          const res = await apiHttp.put<void>(`/v1/sessions/${id}`, { title });
          if (res.ok) {
            _isUsingFallback = false;
            return;
          }
          logger.warn("重命名会话失败", { id, error: res.error });
        } catch (e) {
          handleClientError(e, {
            module: "services:session",
            action: "rename",
          });
          // 网络错误
        }
        const result = await tryTauri<void>("rename_session", { id, title });
        if (result !== null) return;
        return createMemorySessionService().rename(id, title);
      },
    );
  },

  generateTitle: async (
    sessionId: string,
    userMessage: string,
    assistantResponse: string,
  ): Promise<string | null> => {
    try {
      const res = await apiHttp.post<{
        success: boolean;
        title: string | null;
      }>(`/v1/sessions/${sessionId}/title`, { userMessage, assistantResponse });
      if (res.ok) {
        _isUsingFallback = false;
        return (res.data as { title: string | null })?.title ?? null;
      }
      logger.debug("generateTitle 静默降级", { sessionId, error: res.error });
    } catch (e) {
      handleClientError(e, {
        module: "services:session",
        action: "generateTitle",
      });
      // 网络错误
    }
    const result = await tryTauri<{ title: string | null }>(
      "generate_session_title",
      { sessionId, userMessage, assistantResponse },
    );
    return result?.title || null;
  },

  getCurrent: async (): Promise<Session | null> => {
    try {
      const res = await apiHttp.get<Session | null>("/v1/sessions/current");
      if (res.ok) {
        _isUsingFallback = false;
        return flattenSession(res.data as Session | null);
      }
      logger.warn("获取当前会话失败", { error: res.error });
    } catch (e) {
      handleClientError(e, {
        module: "services:session",
        action: "getCurrent",
      });
      // 网络错误
    }
    const result = await tryTauri<Session | null>("get_current_session");
    if (result !== null) return flattenSession(result);
    return createMemorySessionService().getCurrent();
  },

  get: async (id: string): Promise<Session | null> => {
    try {
      const res = await apiHttp.get<Session>(`/v1/sessions/${id}`);
      if (res.ok) {
        _isUsingFallback = false;
        return flattenSession(res.data as Session);
      }
      logger.warn("获取会话失败", { id, error: res.error });
    } catch (e) {
      handleClientError(e, { module: "services:session", action: "get" });
      // 网络错误
    }
    const result = await tryTauri<Session | null>("get_session", { id });
    if (result !== null) return flattenSession(result);
    return createMemorySessionService()
      .list()
      .then((sessions) => sessions.find((s) => s.id === id) || null)
      .catch(() => null);
  },

  getMessages: (sessionId: string): Promise<Message[]> => {
    return getOTelTracing().asyncWrap(
      "services:session:getMessages",
      async () => {
        try {
          const res = await apiHttp.get<Message[]>(
            `/v1/sessions/${sessionId}/messages`,
          );
          if (res.ok) {
            _isUsingFallback = false;
            return res.data ?? [];
          }
          logger.warn("获取会话消息失败", { sessionId, error: res.error });
        } catch (e) {
          handleClientError(e, {
            module: "services:session",
            action: "getMessages",
          });
          // 网络错误
        }
        const result = await tryTauri<Message[]>("get_session_messages", {
          sessionId,
        });
        if (result) return result;
        return [];
      },
    );
  },

  clearAll: async (): Promise<void> => {
    try {
      const res = await apiHttp.delete<void>("/v1/sessions");
      if (res.ok) {
        _isUsingFallback = false;
        return;
      }
      logger.warn("清除所有会话失败", { error: res.error });
    } catch (e) {
      handleClientError(e, { module: "services:session", action: "clearAll" });
      // 网络错误
    }
    const result = await tryTauri<void>("clear_all_sessions");
    if (result !== null) return;
  },

  /**
   * 删除单条消息
   */
  deleteMessage: async (
    sessionId: string,
    messageId: string,
  ): Promise<{ messages: Array<Record<string, unknown>> }> => {
    try {
      const res = await apiHttp.delete<{
        success: boolean;
        messages: Array<Record<string, unknown>>;
      }>(`/v1/sessions/${sessionId}/messages/${messageId}`);
      if (res.ok && res.data) {
        _isUsingFallback = false;
        return { messages: res.data.messages };
      }
    } catch (e) {
      handleClientError(e, {
        module: "services:session",
        action: "deleteMessage",
      });
      throw e;
    }
    throw new Error("Delete message failed");
  },

  /**
   * 截断消息（回退到指定消息之前）
   */
  truncateMessages: async (
    sessionId: string,
    beforeMessageId: string,
  ): Promise<{
    messages: Array<Record<string, unknown>>;
    remainingRollbacks: number;
    undoResults?: Array<{ roundId: number; success: boolean; error?: string }>;
  }> => {
    try {
      const res = await apiHttp.post<{
        success: boolean;
        messages: Array<Record<string, unknown>>;
        remainingRollbacks: number;
        undoResults?: Array<{
          roundId: number;
          success: boolean;
          error?: string;
        }>;
      }>(`/v1/sessions/${sessionId}/messages/truncate`, {
        beforeMessageId,
      });
      if (res.ok && res.data) {
        _isUsingFallback = false;
        return {
          messages: res.data.messages,
          remainingRollbacks: res.data.remainingRollbacks,
          undoResults: res.data.undoResults,
        };
      }
    } catch (e) {
      handleClientError(e, {
        module: "services:session",
        action: "truncateMessages",
      });
      throw e;
    }
    throw new Error("Truncate messages failed");
  },

  /**
   * 更新会话元数据（绑定模型、工作空间等）
   * 后端 PATCH API 不存在时静默降级
   */
  updateSessionMeta: async (
    sessionId: string,
    meta: {
      modelId?: string;
      providerId?: string;
      workspaceId?: string;
      tasksOverride?: Record<string, string>;
    },
  ): Promise<boolean> => {
    try {
      const body: Record<string, unknown> = {};
      if (meta.modelId !== undefined) body.model = meta.modelId;
      if (meta.providerId !== undefined) body.provider_id = meta.providerId;
      if (meta.workspaceId !== undefined) body.workspace_id = meta.workspaceId;
      if (meta.tasksOverride !== undefined)
        body.tasks_override = meta.tasksOverride;
      const res = await apiHttp.patch(`/v1/sessions/${sessionId}/meta`, body);
      if (res.ok) {
        _isUsingFallback = false;
        return true;
      }
    } catch (e) {
      handleClientError(e, {
        module: "services:session",
        action: "updateSessionMeta",
      });
      // 网络错误
    }
    logger.debug("updateSessionMeta 静默降级：PATCH API 不可用", { sessionId });
    return false;
  },

  compact: async (sessionId: string): Promise<unknown | null> => {
    try {
      const res = await apiHttp.post(`/v1/sessions/${sessionId}/compact`);
      if (res.ok) {
        _isUsingFallback = false;
        return res.data;
      }
    } catch (e) {
      handleClientError(e, { module: "services:session", action: "compact" });
      // 网络错误
    }
    logger.debug("compact 静默降级：API 不可用", { sessionId });
    return null;
  },

  prune: async (sessionId: string): Promise<unknown | null> => {
    try {
      const res = await apiHttp.post(`/v1/sessions/${sessionId}/prune`);
      if (res.ok) {
        _isUsingFallback = false;
        return res.data;
      }
    } catch (e) {
      handleClientError(e, { module: "services:session", action: "prune" });
      // 网络错误
    }
    logger.debug("prune 静默降级：API 不可用", { sessionId });
    return null;
  },

  getMemory: async (
    sessionId: string,
    query?: string,
    topK?: number,
  ): Promise<{ items: unknown[]; sessionId: string } | null> => {
    try {
      const params = new URLSearchParams();
      if (query) params.set("q", query);
      if (topK) params.set("topK", String(topK));
      const qs = params.toString();
      const url = `/v1/sessions/${sessionId}/memory${qs ? `?${qs}` : ""}`;
      const res = await apiHttp.get<{ items: unknown[]; sessionId: string }>(
        url,
      );
      if (res.ok) {
        _isUsingFallback = false;
        return res.data as { items: unknown[]; sessionId: string } | null;
      }
    } catch (e) {
      handleClientError(e, { module: "services:session", action: "getMemory" });
      // 网络错误
    }
    logger.debug("getMemory 静默降级：API 不可用", { sessionId });
    return null;
  },

  /**
   * 获取会话制品列表
   * @param sessionId 会话ID
   */
  getArtifacts: async (sessionId: string): Promise<unknown[] | null> => {
    try {
      const res = await apiHttp.get<unknown[]>(
        `/v1/sessions/${sessionId}/artifacts`,
      );
      if (res.ok) {
        _isUsingFallback = false;
        return res.data ?? null;
      }
    } catch (e) {
      handleClientError(e, {
        module: "services:session",
        action: "getArtifacts",
      });
      // 网络错误
    }
    logger.debug("getArtifacts 静默降级：API 不可用", { sessionId });
    return null;
  },

  /**
   * 批量删除会话
   * @param ids 会话ID列表
   */
  batchDelete: async (ids: string[]): Promise<boolean> => {
    try {
      const res = await apiHttp.post("/v1/sessions/batch-delete", { ids });
      if (res.ok) {
        _isUsingFallback = false;
        return true;
      }
    } catch (e) {
      handleClientError(e, {
        module: "services:session",
        action: "batchDelete",
      });
      // 网络错误
    }
    logger.debug("batchDelete 静默降级：API 不可用", { ids });
    return false;
  },
};
