import type { Message, Session } from "../types";
import { httpLegacy as http } from "./httpClient";
import { createLogger } from "../utils/logger";

const logger = createLogger("sessionService");

const isTauri = typeof window !== "undefined" && ("__TAURI__" in window || "__TAURI_INTERNALS__" in window);

// 是否已降级到内存模式（后端不可用时设为 true）
let _isUsingFallback = false;

/** 获取当前是否处于降级模式 */
export function isUsingFallback(): boolean {
  return _isUsingFallback;
}

async function getTauriCore() {
  if (!isTauri) return null;
  try {
    return await import("@tauri-apps/api/core");
  } catch {
    return null;
  }
}

function createMemorySessionService() {
  _isUsingFallback = true;
  return {
    list: async (): Promise<Session[]> => [],
    create: async (title: string): Promise<Session> => ({
      id: `local-${Date.now()}`,
      title,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      messageCount: 0,
      roundCount: 0,
    }),
    switch: async (_id: string): Promise<Session> => ({
      id: _id,
      title: "恢复的会话",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      messageCount: 0,
      roundCount: 0,
    }),
    delete: async (_id: string): Promise<void> => {},
    rename: async (_id: string, _title: string): Promise<void> => {},
    getCurrent: async (): Promise<Session | null> => null,
  };
}

async function tryTauri<T>(
  method: string,
  args?: Record<string, unknown>,
): Promise<T | null> {
  const core = await getTauriCore();
  if (!core) return null;
  try {
    return await core.invoke<T>(method, args);
  } catch {
    return null;
  }
}

/**
 * 展平 metadata 字段到顶级（BUG #12 展平修复）
 * 后端在 metadata 中存储 titleAutoGenerated，统一提取到顶层字段
 * 同时提取 model → modelId, workspaceId, tasksOverride 等会话绑定资源
 */
function flattenSession<S extends Session | null>(session: S): S {
  if (!session) return session;
  const raw = session as unknown as {
    metadata?: {
      titleAutoGenerated?: boolean;
      model?: string;
      workspaceId?: string;
      providerId?: string;
      workspacePath?: string;
      tasksOverride?: Record<string, string>;
    };
  };
  return {
    ...session,
    titleAutoGenerated: raw.metadata?.titleAutoGenerated,
    modelId: raw.metadata?.model || session.modelId,
    providerId: raw.metadata?.providerId || session.providerId,
    workspaceId: raw.metadata?.workspaceId || session.workspaceId,
    workspacePath: raw.metadata?.workspacePath || (session as { workspacePath?: string }).workspacePath,
    tasksOverride: (raw.metadata?.tasksOverride as Record<string, string> | undefined) || session.tasksOverride,
  };
}

/**
 * 创建会话
 * @param title 会话标题
 * @param options 可选：绑定模型ID、工作空间ID
 */
export const sessionService = {
  list: async (): Promise<Session[]> => {
    try {
      const result = await http.get<Session[]>("/v1/sessions");
      _isUsingFallback = false;
      return result.map(flattenSession);
    } catch {
      const result = await tryTauri<Session[]>("list_sessions");
      if (result) return result.map(flattenSession);
      return createMemorySessionService().list();
    }
  },

  create: async (
    title: string,
    options?: { modelId?: string; workspaceId?: string; workspacePath?: string }
  ): Promise<Session> => {
    try {
      const body: Record<string, unknown> = { title };
      if (options?.modelId) body.model = options.modelId;
      if (options?.workspaceId) body.workspaceId = options.workspaceId;
      if (options?.workspacePath) body.workspace_path = options.workspacePath;
      const result = await http.post<Session>("/v1/sessions", body);
      _isUsingFallback = false;
      return flattenSession(result);
    } catch {
      const result = await tryTauri<Session>("create_session", { title });
      if (result) return flattenSession(result);
      return createMemorySessionService().create(title);
    }
  },

  switch: async (id: string): Promise<Session> => {
    try {
      const result = await http.post<Session>(`/v1/sessions/${id}/switch`);
      _isUsingFallback = false;
      return flattenSession(result);
    } catch {
      const result = await tryTauri<Session>("switch_session", { id });
      if (result) return flattenSession(result);
      return createMemorySessionService().switch(id);
    }
  },

  delete: async (id: string): Promise<void> => {
    try {
      await http.delete<void>(`/v1/sessions/${id}`);
      _isUsingFallback = false;
    } catch {
      const result = await tryTauri<void>("delete_session", { id });
      if (result !== null) return;
      return createMemorySessionService().delete(id);
    }
  },

  rename: async (id: string, title: string): Promise<void> => {
    try {
      await http.put<void>(`/v1/sessions/${id}`, { title });
      _isUsingFallback = false;
    } catch {
      const result = await tryTauri<void>("rename_session", { id, title });
      if (result !== null) return;
      return createMemorySessionService().rename(id, title);
    }
  },

  generateTitle: async (
    sessionId: string,
    userMessage: string,
    assistantResponse: string,
  ): Promise<string | null> => {
    try {
      const response = await http.post<{
        success: boolean;
        title: string | null;
      }>(`/v1/sessions/${sessionId}/title`, { userMessage, assistantResponse });
      _isUsingFallback = false;
      return response.title;
    } catch {
      const result = await tryTauri<{ title: string | null }>(
        "generate_session_title",
        {
          sessionId,
          userMessage,
          assistantResponse,
        },
      );
      return result?.title || null;
    }
  },

  getCurrent: async (): Promise<Session | null> => {
    try {
      const result = await http.get<Session | null>("/v1/sessions/current");
      _isUsingFallback = false;
      return flattenSession(result);
    } catch {
      const result = await tryTauri<Session | null>("get_current_session");
      if (result !== null) return flattenSession(result);
      return createMemorySessionService().getCurrent();
    }
  },

  get: async (id: string): Promise<Session | null> => {
    try {
      const result = await http.get<Session>(`/v1/sessions/${id}`);
      _isUsingFallback = false;
      return flattenSession(result);
    } catch {
      const result = await tryTauri<Session | null>("get_session", { id });
      if (result !== null) return flattenSession(result);
      return createMemorySessionService()
        .list()
        .then((sessions) => sessions.find((s) => s.id === id) || null);
    }
  },

  getMessages: async (sessionId: string): Promise<Message[]> => {
    try {
      const result = await http.get<Message[]>(`/v1/sessions/${sessionId}/messages`);
      _isUsingFallback = false;
      return result;
    } catch {
      const result = await tryTauri<Message[]>("get_session_messages", {
        sessionId,
      });
      if (result) return result;
      return [];
    }
  },

  clearAll: async (): Promise<void> => {
    try {
      await http.delete<void>("/v1/sessions");
      _isUsingFallback = false;
    } catch {
      const result = await tryTauri<void>("clear_all_sessions");
      if (result !== null) return;
    }
  },

  /**
   * 更新会话元数据（绑定模型、工作空间等）
   * 后端 PATCH API 不存在时静默降级
   */
  updateSessionMeta: async (
    sessionId: string,
    meta: { modelId?: string; providerId?: string; workspaceId?: string; tasksOverride?: Record<string, string> }
  ): Promise<boolean> => {
    try {
      const body: Record<string, unknown> = {};
      if (meta.modelId !== undefined) body.model = meta.modelId;
      if (meta.providerId !== undefined) body.provider_id = meta.providerId;
      if (meta.workspaceId !== undefined) body.workspace_id = meta.workspaceId;
      if (meta.tasksOverride !== undefined) body.tasks_override = meta.tasksOverride;
      await http.patch(`/v1/sessions/${sessionId}/meta`, body);
      _isUsingFallback = false;
      return true;
    } catch {
      // PATCH API 不可用，静默降级
      logger.debug("updateSessionMeta 静默降级：PATCH API 不可用", { sessionId });
      return false;
    }
  },

  compact: async (sessionId: string): Promise<unknown | null> => {
    try {
      const result = await http.post(`/v1/sessions/${sessionId}/compact`);
      _isUsingFallback = false;
      return result;
    } catch {
      logger.debug("compact 静默降级：API 不可用", { sessionId });
      return null;
    }
  },

  prune: async (sessionId: string): Promise<unknown | null> => {
    try {
      const result = await http.post(`/v1/sessions/${sessionId}/prune`);
      _isUsingFallback = false;
      return result;
    } catch {
      logger.debug("prune 静默降级：API 不可用", { sessionId });
      return null;
    }
  },

  getMemory: async (
    sessionId: string,
    query?: string,
    topK?: number
  ): Promise<{ items: unknown[]; sessionId: string } | null> => {
    try {
      const params = new URLSearchParams();
      if (query) params.set('q', query);
      if (topK) params.set('topK', String(topK));
      const qs = params.toString();
      const url = `/v1/sessions/${sessionId}/memory${qs ? `?${qs}` : ''}`;
      const result = await http.get<{ items: unknown[]; sessionId: string }>(url);
      _isUsingFallback = false;
      return result;
    } catch {
      logger.debug("getMemory 静默降级：API 不可用", { sessionId });
      return null;
    }
  },

  /**
   * 获取会话制品列表
   * @param sessionId 会话ID
   */
  getArtifacts: async (sessionId: string): Promise<unknown[] | null> => {
    try {
      const result = await http.get<unknown[]>(`/v1/sessions/${sessionId}/artifacts`);
      _isUsingFallback = false;
      return result;
    } catch {
      logger.debug("getArtifacts 静默降级：API 不可用", { sessionId });
      return null;
    }
  },

  /**
   * 批量删除会话
   * @param ids 会话ID列表
   */
  batchDelete: async (ids: string[]): Promise<boolean> => {
    try {
      await http.post("/v1/sessions/batch-delete", { ids });
      _isUsingFallback = false;
      return true;
    } catch {
      logger.debug("batchDelete 静默降级：API 不可用", { ids });
      return false;
    }
  },
};
