/**
 * Session Store — rootStore 的薄封装（零重复状态）
 *
 * 所有状态真实存储在 useRootStore.sessionSlice 中。
 * useSessionStore 是一个 Zustand store 镜像，通过 subscribe 自动同步 rootStore 变更。
 * 组件使用方式和 API 完全不变。
 *
 * 迁移完成后，组件可逐步迁移到 useRootStore 直接取值。
 */

import { create } from "zustand";
import { persist } from "zustand/middleware";
import { Session } from "../types";
import { useRootStore } from "./root-store";

interface SessionStore {
  sessions: Session[];
  currentSession: Session | null;
  isLoading: boolean;
  switching: boolean;
  error: string | null;
  pinnedSessionIds: string[];
  loadSessions: () => Promise<void>;
  createSession: (title: string) => Promise<Session>;
  switchSession: (id: string) => Promise<void>;
  deleteSession: (id: string) => Promise<void>;
  renameSession: (id: string, title: string) => Promise<void>;
  clearAllSessions: () => Promise<void>;
  togglePin: (id: string) => void;
  isPinned: (id: string) => boolean;
}

/**
 * 从 rootStore 派生当前 sessionStore 镜像状态
 */
function deriveState(root: ReturnType<typeof useRootStore.getState>): {
  sessions: Session[];
  currentSession: Session | null;
  isLoading: boolean;
  switching: boolean;
  error: string | null;
  pinnedSessionIds: string[];
} {
  const currentId = root.currentSessionId;
  return {
    sessions: root.chatSessions ?? [],
    currentSession: currentId
      ? (root.chatSessions ?? []).find((s) => s.id === currentId) ?? null
      : null,
    isLoading: root.isLoading,
    switching: root.switching,
    error: root.error,
    pinnedSessionIds: root.pinnedSessionIds ?? [],
  };
}

/**
 * sessionStore — rootStore 的 Zustand 镜像
 *
 * 自身也有 persist（向后兼容 localStorage 中的 "liri-sessions" 键），
 * 但 hydrate 后立即同步到 rootStore。
 */
export const useSessionStore = create<SessionStore>()(
  persist(
    () => ({
      ...deriveState(useRootStore.getState()),

      loadSessions: () => useRootStore.getState().loadChatSessions(),
      createSession: (title) => useRootStore.getState().createChatSession(title),
      switchSession: (id) => useRootStore.getState().switchChatSession(id),
      deleteSession: (id) => useRootStore.getState().deleteChatSession(id),
      renameSession: (id, title) => useRootStore.getState().renameChatSession(id, title),
      clearAllSessions: () => useRootStore.getState().clearAllChatSessions(),
      togglePin: (id) => useRootStore.getState().togglePin(id),
      isPinned: (id) => useRootStore.getState().isPinned(id),
    }),
    {
      name: "liri-sessions",
      partialize: (state) => ({
        sessions: state.sessions.map((s) => ({
          id: s.id,
          title: s.title,
          updatedAt: s.updatedAt,
          titleAutoGenerated: s.titleAutoGenerated,
          modelId: s.modelId,
          providerId: s.providerId,
          workspaceId: s.workspaceId,
          workspacePath: s.workspacePath,
          tasksOverride: s.tasksOverride,
        })),
        pinnedSessionIds: state.pinnedSessionIds,
      }),
      // 反序列化时：恢复旧数据到 rootStore
      onRehydrateStorage: () => (state, error) => {
        if (error || !state) return;
        // 将旧 persist 数据迁移到 rootStore
        const root = useRootStore.getState();
        if (state.sessions?.length && root.chatSessions.length === 0) {
          useRootStore.setState((s) => ({ ...s, chatSessions: state.sessions as Session[] }));
        }
        if (state.pinnedSessionIds?.length) {
          useRootStore.setState((s) => ({ ...s, pinnedSessionIds: state.pinnedSessionIds }));
        }
        if (state.currentSession) {
          useRootStore.setState((s) => ({ ...s, currentSessionId: (state.currentSession as Session).id }));
        }
      },
    },
  ),
);

// ─── 核心：rootStore → sessionStore 单向镜像 ────────────
// rootStore 是唯一事实来源，sessionStore 只是它的投影。
// 任何 rootStore 变更自动同步到 sessionStore，保证「数出同源」。

useRootStore.subscribe((root) => {
  useSessionStore.setState(deriveState(root));
});

// 状态变更日志（仅开发环境）
import { withStoreLogging } from "../utils/storeLogger";
withStoreLogging(useSessionStore, "sessionStore", []);
